### PR TITLE
panacea 2

### LINKED ISSUE #68: Define <word> not working properly.
- `shell` zsh
- `Operating system/version`: artix
- `Terminal name/version`: st
- `$TERM` st

## Steps to Reproduce the Problem
`tuxi define humor`

## Expected Behavior
The funny or amusing qualities of somebody/something

## Actual Behavior
No Results!

I believe this https://github.com/Bugswriter/tuxi/pull/64 isn't working properly ..this may be because ..this issue of using tuxi as a dictionary by scraping ..define <word> is not simple. Sometimes google give multiple response. See this -

image

### PR DESCRIPTION
**Pull request by Genghius**
image
passes every test, fixes #68 
Try accepting only PR's that pass the test script btw, else its difficult to keep track with the constantly breaking versions.

### CODE REVIEW

**Comment by Genghius** [comment]
Once this is merged with develop, also pass it to main @Bugswriter .

**Comment by BeyondMagic** [comment]
> # Please do not try to make this script any more fancy or extensible, just leave it as is.

lol

**Comment by Genghius** [comment]
> > Please do not try to make this script any more fancy or extensible, just leave it as is.
> 
> lol

xd, btw define is no longer breaking. but it still isnt difining words, it is just returning the word, can you make a PR to fix that once this one is merged?

**Comment by Bugswriter** [comment]
> > Please do not try to make this script any more fancy or extensible, just leave it as is.
> 
> lol

no we can add more features. that's not the issue. We need to try scrape as much info as we get though google search result. But we need to do carefully and make sure our features are working.

**Comment by Genghius** [comment]
> > > Please do not try to make this script any more fancy or extensible, just leave it as is.
> > 
> > 
> > lol
> 
> no we can add more features. that's not the issue. We need to try scrape as much info as we get though google search result. But we need to do carefully and make sure our features are working.

that was refering to the test script xd, its so that people dont break it again xxdxdxdxd.

**Comment by BeyondMagic** [comment]
> xd, btw define is no longer breaking. but it still isnt difining words, it is just returning the word, can you make a PR to fix that once this one is merged?

Yes, I'm looking at it.

**Comment by Bugswriter** [comment]
> > > Please do not try to make this script any more fancy or extensible, just leave it as is.
> > 
> > 
> > lol
> 
> xd, btw define is no longer breaking. but it still isnt difining words, it is just returning the word, can you make a PR to fix that once this one is merged?

yeah I was looking into this. I believe .. everytime we get something like this from google. - 
image

We need to scrape this in form of list. 
Also we have to do this. Because .. This will be weird for a program like Tuxi which can answer so many things.
 Can't define humor?

**Comment by BeyondMagic** [comment]
> We need to scrape this in form of list.

I'll make a PR soon adding that.

**Comment by Genghius** [comment]
ok, dont merge this pr yet, gimme 10 more minutes to fix it.

**Comment by BeyondMagic** [comment]
`Rich answers` is in conflict with `define`, define must be scrapped first @Bugswriter.

**Comment by Genghius** [comment]
after its merged to develop, merge to main too.

**Comment by Bugswriter** [comment]
Let me resolve some conflicts and I will merge this into develop but. We will not pull this to main yet. We will test things first.

**Comment by Genghius** [comment]
> Let me resolve some conflicts and I will merge this into develop but. We will not pull this to main yet. We will test things first.

sure.

**Pull request merged**
