### PR TITLE
Weather Condition

### PR DESCRIPTION
**Pull request by jhagas**
It's working but it's greatly inefficient. Can anyone improve it?

```
➤ tuxi weather bojonegoro
---
"Cloudy"
28 ºC
82 ºF
---
```

### CODE REVIEW

**Comment by Bugswriter** [comment]
Nice work. Lets see someone improve your code quality.
But since now before adding anything. I need a proper test response with a variety of questions.
Not just two or three at least weather for 20 cities.

**Comment by jhagas** [comment]
Screenshot from 2021-02-19 14-30-02

Screenshot, i test it with every cities that i know

**Comment by owl4ce** [comment]
image

**Comment by Bugswriter** [comment]
are we ready for merge?

**Comment by jhagas** [comment]
I'm using cut and rev command. While it is working, but i think sed is better. Sadly, i dont understand it (i'm new in linux and shell scripting). Can sed do the exact same stuff?

How my commit work? by pup-ing image line in google html code
```pup 'img.wob_tci'```. Then removing some word and letter in that line of code and leaving the "weather condition" phrase inside the image alt info

**Comment by Bugswriter** [comment]
> I'm using cut and rev command. While it is working, but i think sed is better. Sadly, i dont understand it (i'm new in linux and shell scripting). Can sed do the exact same stuff?
> 
> How my commit work? by pup-ing image line in google html code
> `pup 'img.wob_tci'`. Then removing some word and letter in that line of code and leaving the "weather condition" phrase inside the image alt info

@officialcactar ?

**Comment by Genghius** [comment]
#111 uses only awk and sed as per author's request. @Bugswriter

**Comment by Bugswriter** [comment]
> #111 uses only awk and sed as per author's request. @Bugswriter

@Genghius I think we can merge this PR directly into main.. This is not doing much. also it's well tested?

**Comment by Bugswriter** [comment]
I am thinking about adding working features safely in main

**Comment by Genghius** [comment]
This pr can be closed now.

**Comment by Bugswriter** [comment]
@jhagas You did a good job.

**Pull request closed without merging**
