### PR TITLE
Read Me: Installation and update instruction

### PR DESCRIPTION
**Pull request by owl4ce**
@Bugswriter

### CODE REVIEW

**Comment by owl4ce** [comment]
Wait for a while

**Comment by owl4ce** [comment]
@Bugswriter 

How?

**Comment by Bugswriter** [comment]
ok

**Comment by owl4ce** [comment]
wait typos

**Comment by Bugswriter** [comment]
I guess now we only need to convert our features into functions and do a mass testing.  Then we will be able to merge develop into main. may be adding two more feature PR we have.

**Comment by owl4ce** [comment]
Done

**Pull request merged**
