### PR TITLE
Fixed/optimized/added some things v2

### PR DESCRIPTION
**Pull request by BeyondMagic**
#69375d3 rewrote `Define` snippet, now it give us the word itself, mode (verb, noun), and meanings
#ef49677 optimized code and added option to return all snippets `-a`
#6994e2e fixed rich answers for #89, please test for secondary text as well, like `social network text`
#d7f4915 gives location for future fixes, like in lyrics
#cdda220 only add the changes to readme and -h of tuxi.

### CODE REVIEW

**Comment by BeyondMagic** [comment]
image

New options shown.

**Comment by Bugswriter** [comment]
You fixed tuxi for NFS list fetch? But try searching the social network cast.

**Comment by BeyondMagic** [comment]
I know, it's not working, I'm looking at it right now. This isn't ready to merge.

**Comment by BeyondMagic** [comment]
@Bugswriter there you go.

**Comment by Bugswriter** [comment]
Seriously you did awesome job man. Glad you have you in team.

**Comment by Bugswriter** [comment]
I think your PR did fix https://github.com/Bugswriter/tuxi/issues/91 but haven't fix define. 
You rewrote define but I can't use it. 
try - `tuxi define fuck`
No result. 
also I am getting very ugly list like this  when I do

`tuxi define power`

```
[1;32m---[0m
View all
 
 
Work
 
 
Energy
 
 
Electric current
 
 
Momentum
 
 
Physics
 
 
Time
 
 
Efficiency

View all 
[1;32m---[0m
```

**Comment by BeyondMagic** [comment]
I'm back, I know you did go to sleep, but I'll leave this here. It's working here, I don't know if this is a problem with Google & location showing different results, or if it was something I did remove, anyway, to make sure I'll make a PR already read to merge.

image

**Comment by Bugswriter** [comment]
image

we have to do something for define. It should work. But it seems it's not working for every word. Patriotic.
If you try to fix this now .. make a list of some english words and run loop.

**Pull request merged**
