### PR TITLE
Optimized code

### PR DESCRIPTION
**Pull request by BeyondMagic**
To test this code, just do
```bash
git clone https://github.com/BeyondMagic/tuxi.git bmtuxi
cd bmtuxi
./tuxi "linus torvalds"
./tuxi ".............."
```

The code was simplified using a function to scrap the HTML, it's very simple.

### CODE REVIEW

**Comment by Genghius** [comment]
if we are going function, i would preffer ever scrap being its own function.

**Comment by Bugswriter** [comment]
Nice I was waiting for this.
This is even better than the current develop branch snipcall function.
Does it pass all the tests?
Did you test everything properly?

**Comment by Bugswriter** [comment]
@Genghius yeah .. you are right every scape being it's own function. But it depends on how many features we want?
I guess we will end up with hardly 15-20 features max. and This function @BeyondMagic removing the redundancy in code.
I guess we can extend like the way you proposing different functions for different feature.

**Comment by Genghius** [comment]
yeh, maybe i'll turn eerything into functions with my next PR, passing this one will help lots.

**Comment by BeyondMagic** [comment]
@Genghius yeah, I did this thinking in portability, it's way easier to maintain the script with the code like this, at least for someone who uses only a few features, this should help disabling and enabling them.

@Bugswriter  I did test everything, even though there's no changes at the scrapping itself, and it worked as far I as remember,   but I left a "mini tutorial" there to hope that you guys would test it out before merging.

**Comment by Bugswriter** [comment]
I will look into this and merge soon

**Comment by sudocanttype** [comment]
Just ran the testcases on my end (US), and everything looks good.
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6023723/testoutputs.txt)

**Comment by Bugswriter** [comment]
Cool I am merging this.

**Pull request merged**
