### PR TITLE
fix (flip-flop) weather output units

### PR DESCRIPTION
**Pull request by zachspar**
I have opened issue #112, and mentioned I would open a PR with the simple change.

### CODE REVIEW

**Comment by Genghius** [comment]
if my PR gets passed, this wont be needed.

**Comment by zachspar** [comment]
Agreed, however this fixes an issue.  Your change is an enhancement that could cause more issues, in addition to fixing #112.

**Comment by colonvirus** [comment]
I assume you're in the US.

This isn't a fix.
`pup 'div.TylWce text{}' ` returns two lines for most countries:
First is Celsius,
Second is Fahrenheit.

But this is the opposite for the US (\+ a few others).

`sed -e '1 s/$/ ºC/' -e '2 s/$/ ºF/'` just appends ºC to the first line, and ºF to the second.

Your change appends ºF to the first line, and ºC to the second, and it works for you, but not others.

@Genghius, your improvements rely on the same concept too, so yea, you need to fix that 😄

**Comment by zachspar** [comment]
> This isn't a fix.
> 
> `pup 'div.TylWce text{}' ` returns two lines for most countries:
> 
> First is Celsius,
> 
> Second is Fahrenheit.
> 
> But this is the opposite for the US (\+ a few others).

Thank you for this information @colonvirus, and I'm surprised I didn't realize this sooner 🤦‍♂️. I'm no `sed` or `awk` wizard, but this gives me a nice opportunity to experiment and find a solution, that supports everyone who uses `tuxi` 😉

**Comment by Bugswriter** [comment]
> if my PR gets passed, this wont be needed.

I can pass your PR but our develop branch is messed?

**Comment by Genghius** [comment]
> > if my PR gets passed, this wont be needed.
> 
> I can pass your PR but our develop branch is messed?

if we just copy my weather snippet into the development branch it'll work just fine. 
imma pass the PR rigth now, this one can be closed.

**Pull request closed without merging**
