### PR TITLE
Getopts, cleaner code?, comments explaining each snippet scraper

### PR DESCRIPTION
**Pull request by colonvirus**
take a looksie

### CODE REVIEW

**Comment by colonvirus** [comment]
I do not know what
`res1="$(echo "$google_html" | pup 'div.zCubwf text{}' | tr -d '\n' | recode html..ISO-8859-1)"`
does.

**Comment by Genghius** [comment]
this will need to be rewritten a little once PR #31 and #32 are merged

**Comment by colonvirus** [comment]
I had fixed #30

**Comment by Genghius** [comment]
> I had fixed #30

nice

**Comment by colonvirus** [comment]
Oo, and i forgot
I added a quiet option to silence "did you mean?" and tuxi's greeting
Good for dunst

**Comment by Bugswriter** [comment]
I am getting some merge conflicts here. Can someone help me with this?

**Comment by colonvirus** [comment]
yea wait

**Pull request merged**
