### PR TITLE
Babe it's time for your daily pull request; Yes honey

### PR DESCRIPTION
**Pull request by PureArtistry**
did my first bit of html scraping today, noticed the scores were the wrong way around for the sports fixture snippet, figured I'd fix it...
then I thought I may as well move them up next to the team names...
then I re-wrote the whole thing
scrot_20210303-190933

### CODE REVIEW

**Comment by BeyondMagic** [comment]
my god, that's so big

**Comment by PureArtistry** [comment]
what do you mean? the number of lines?

**Comment by PureArtistry** [comment]
need to tweak the output for if a match is in progress, haven't been able to test it until now - it does work properly
and it does need recode after all it seems

**Comment by BeyondMagic** [comment]
> what do you mean? the number of lines? the cat?

Yeah, the number of lines, can you add some comments on the while loop?

**Comment by PureArtistry** [comment]
will do, even though it's a lot of lines it's actually really efficient as the only external things being run are pup and recode.
everything else, all of the formatting, is done exclusively with builtins and most of those are conditions that won't be met on any given run so a lot of that code doesn't get executed

**Comment by BeyondMagic** [comment]
>even though it's a lot of lines it's actually really efficient as the only external things being run are pup and recode.
everything else, all of the formatting, is done exclusively with builtins and most of those are conditions that won't be met on any given run so a lot of that code doesn't get executed

ok

**Comment by PureArtistry** [comment]
I think this might be ready now, will need testing for other sports to see if the formatting works for stuff other than football

**Comment by BeyondMagic** [comment]
damn, man made a book, good for developers reading in the future

**Comment by BeyondMagic** [comment]
image

for american football

**Comment by PureArtistry** [comment]
damn, guess it's going to need a little more work, probably won't be until the weekend though - I bet a lot of the different sports are going to have slightly different arrangements

**Comment by BeyondMagic** [comment]
yeah, formatting it beautifully like you did will take a lot of time to different sports, is there anyway we can generalize it and make it less, let's say, pretty?

**Comment by PureArtistry** [comment]
the only way to generalise it would be to put it back how it was with it just spitting out one bit of info per line (how it was) and you just have to make sense of it

with each different sport (and different "states" of those games within each sport) the order of a lot of the info changes, there do seem to be some constants though, like the league being on line 3

I doubt it would really take that long for me to format the rest of the stuff, I just need cache files for the different sports and match states. I know nothing about american sports so I'll need help knowing what keywords to use.
if anybody wants to post the file created by using the -s option for sports they know, it will make doing the other formatting much easier and faster

**Comment by BeyondMagic** [comment]
I mean, in certain ways that's good, but one day we will need to maintain all those scrapings and with more and more conditions, this will be harder. But some conditions, like if the match still happening, can be generalized as well, can't they? Instead of just printing everything at one line, why doesn't make states of the sports and printing scores at a separate line, etc. Anyway, this all talk so I will try to do it right now.

**Comment by BeyondMagic** [comment]
I'm just having too many problems with loading matches overall, I'm giving up...

**Comment by Genghius** [comment]
> my god, that's so big

that's what she said.

**Comment by Bugswriter** [comment]
that's such a cool feature. Amazing job. You are truly a pro. 
is it ready?
tomorrow is my final exam. Your PR will get passed more quickly.

**Comment by Bugswriter** [comment]
that's such a cool feature. Amazing job. You are truly a pro. 
is it ready?
tomorrow is my final exam. Your PR will get passed more quickly. 
Also please work on surety of merging this with main.

**Comment by BeyondMagic** [comment]
> > my god, that's so big
> 
> that's what she said.

BREAKING NEWS: man with anime picture just got a girl, UNBELIEVABLE!

**Comment by Genghius** [comment]
> > > my god, that's so big
> > 
> > 
> > that's what she said.
> 
> BREAKING NEWS: man with anime picture just got a girl, UNBELIEVABLE!

nevermind, we broke up.
She made me choose between my waifu and her.

**Comment by PureArtistry** [comment]
just the define snippet to go

@Genghius my condolences for your relationship woes

**Comment by PureArtistry** [comment]
was busy yesterday, sorry.

had to re-work the define snippet entirely, the last version worked great until the format of the html deviated slightly and then it fell on it's arse and just spat out unreadable junk :(

started from scratch, scraping a different div and the results are much better now anyway, plus this one *seems* bulletproof.

scrot_20210307-095618

@Bugswriter - I think this may be ready now unless anybody has found any bugs?

**Comment by Bugswriter** [comment]
that was so good. I love this define functions and your system. Waiting to merge this with main.

**Comment by PureArtistry** [comment]
> that was so good. I love this define functions and your system. Waiting to merge this with main.

thanks! :)

**Comment by PureArtistry** [comment]
found something to trip the new define snippet up slightly (it's not that bad), working on a fix now though, shouldn't take long

**Comment by PureArtistry** [comment]
sorted (until the next word that has inconsistant formatting in the html)

**Comment by PureArtistry** [comment]
I have realised that this define snippet is only going to work if your language is english
going to need figure out the different lang codes and get the translations for word types (noun, verb etc) and update the snippet with all the different lang variations

**Comment by PureArtistry** [comment]
bollocks, I'm going to need help with making this work with other languages. I just tried checking out the definitions in french and realised it's going to take me ages to get all the various word type translations.

going to tweak the script to only use the new define if your lang is en_*

**Comment by Genghius** [comment]
Lets just force the language to be english and leave the actual language to the user's common sense.
(**weather Cº Fº flashbacks intensify**)

**Comment by PureArtistry** [comment]
@Genghius - that's kind of what it is now, I don't mind putting in the work and making it work for other languages if somebody else is willing to send me a list of all possible word types for their language (according to how google displays it)

I look for a list in french for instance and the list I found was slightly different to how it was displayed on the google results which is why I gave up on the idea of doing it myself - I don't know enough foreign langs for it to be efficient to try

**Comment by PureArtistry** [comment]
@Bugswriter - aside from bug fixes (if needed) this is going to be my last commit to this, just going to wait now until everything's merged before I start fiddling with it again.

**Comment by BeyondMagic** [comment]
In japanese it's complete different, the older version gives the meanings, though

image

**Comment by PureArtistry** [comment]
I'm betting now that that was the rich snippet rather than define, may need to mess with priority a bit more again
if you do -a it should have the same answer as the old one

**Comment by BeyondMagic** [comment]
Nevermind, I was using the wrong version, the new one gives a second meaning and an example

image

**Comment by PureArtistry** [comment]
does that look right though? I have no clue what I'm looking at (and is that with tuxi's lang set to english?)

**Comment by BeyondMagic** [comment]
this is what Google gives, it's not perfect

image

> and is that with tuxi's lang set to english?

JA_JP. You should add a new parameter in the .gitub_templates (issues) for the language of the system.

**Comment by PureArtistry** [comment]
scrot_20210307-160414

top one is with my system lang (en_GB) and as you can see if I change my lang to jp it uses a different snippet

how much of a mess does the english version look? (I can't read that)

**Comment by BeyondMagic** [comment]
> how much of a mess does the english version look?

It's good enough, how did you get the second one?

I can only repeat the first output

**Comment by PureArtistry** [comment]
> > how much of a mess does the english version look?
> 
> It's good enough, how did you get the second one?
> 
> I can only repeat the first output

```
a_define() { # Define (eg: define Aggrandize) //original snippet credit @igaurab
    case "$LANGUAGE" in
    en_*) dfn_use_new=true ;;
    *) dfn_use_new=false ;;
    esac
```
I used the -l flag to change my language to japanese, it will only use the new define code if your tuxi language is set to english

**Comment by BeyondMagic** [comment]
> I used the -l flag to change my language to japanese, it will only use the new define code if your tuxi language is set to english

I see... nice feature.

**Comment by PureArtistry** [comment]
I know I said I would stop fiddling but I got bored.
was looking to maybe optimise some of the functions, after a bit of testing discovered that the rich snippet was basically redundant and the div that it scraping caused problems for other snippets

this is why on main you can't put rich above define, rich grabbed from div.XcVN5d. XcVN5d is the suffix used for the headline of answers that appear at the top, the different types of answers have a different prefix.
for eample kno_val uses Z0LcW.XcVN5d and for definitions on the google page, the word you are looking up is DgZBFd.XcVN5d.frCXef. rich was grabbing that before define could print out what you wanted.

the other 2 scrapes in the rich function got more lyrics (the 2 lyrics scrapes we have already grab everything) and the other similar info to kno_right.

so in the end I scrapped the function but left the 2 good (but not needed) div labels in comments in case they become useful again.

also the list snippet tended to mangle a lot of the output

scrot_20210308-173844

this is because all the formatting for the lists was done with html tags, each tag appearing on a new line. google highlights keywords you used in bold and those tags split up the text over multiple line, messing up the output.

I re-wrote the snippet and instead of having pup strip out the html, I left it in and used it to rebuild the output (mostly) correctly - it's not always exactly as it should be, sometimes there are extra spaces but that's easier to ignore than sentences split across multiple lines in weird places.

scrot_20210308-173947

**Comment by PureArtistry** [comment]
still bored, added a new feature; the -u flag

scrot_20210309-000250

if you add the flag, at the end of every query it will print out google's list of top urls

scrot_20210309-000446

or if you search for something and get no results it will print out automatically

scrot_20210309-000611

the no results for that is a google thing btw, sometimes it gives you the html with the list, sometimes it doesn't - google be strange sometimes
(I checked this in the browser too btw)

**Comment by PureArtistry** [comment]
@Bugswriter - now I think I'm done messing with it (kinda run out of ideas)

**Comment by BeyondMagic** [comment]
@Bugswriter you there?

**Comment by Bugswriter** [comment]
yes

**Comment by BeyondMagic** [comment]
it's time, isn't?

**Comment by PureArtistry** [comment]
noticed some activity on here so I took another quick look at the script this morning; small update, found out what the mR2gOd div was for and added a tracklist snippet
scrot_20210317-124145

**Pull request closed without merging**
