### PR TITLE
sed fuckery

### PR DESCRIPTION
**Pull request by Genghius**
Hippity hoppity, Now your script uses sed fuckery!
xd

### CODE REVIEW

**Comment by Genghius** [comment]
image
tests ^

**Comment by sudocanttype** [comment]
nice, regex is hard. I'm gonna run it through the tests on my side to make sure everything is working

**Comment by sudocanttype** [comment]
It looks like everything that you changed is working perfectly. However, there is still a bug for US users that outputs swapped C and F values, likely because we americans are stupid and still use F as default.
image
Also, how did you take that super long screenshot?

**Comment by Genghius** [comment]
> It looks like everything that you changed is working perfectly. However, there is still a bug for US users that outputs swapped C and F values, likely because we americans are stupid and still use F as default.
> image
> Also, how did you take that super long screenshot?

we wont do anything about americans not being able to use normal measurement units for now...
However, the long screenshot was taken by rotating my 2 screens, so the terminal was 3840px long

**Comment by Bugswriter** [comment]
It looks like you changed a lot of stuff in this PR

**Comment by Bugswriter** [comment]
are you sure .. merging this with main? .. will everything remain same?

**Comment by Genghius** [comment]
> It looks like you changed a lot of stuff in this PR

nothing was really changed, I just translated everything that I could into sed only for the sakes of the meme.

**Comment by Genghius** [comment]
> are you sure .. merging this with main? .. will everything remain same?

I ran it through the test script and it showed no issues. However, I would prefer this PR isn't merged until someone runs it trough a few edge cases and tests.

**Comment by sudocanttype** [comment]
In theory, not much is actually changed. Its just some awk and tr functions were converted to sed functions, and some sed functions were merged into 1 liners

**Comment by sudocanttype** [comment]
The only change I see that could cause problems is line 180, because I don't understand how the hell it works. Everything else is/should be fine.

**Pull request merged**
