### PR TITLE
added weather support [waiting for #39 pass]

### PR DESCRIPTION
**Pull request by BeyondMagic**
e.g.:

```
$ tuxi weather new york
---
-1 ºC
31 ºF
---
```

I think that the sed with ºC and ºF is good, but obviously we can remove them for easier extensibility

### CODE REVIEW

**Comment by owl4ce** [comment]
This needs to be changed to https://github.com/Bugswriter/tuxi/pull/39, if all tests are safe.

**Comment by BeyondMagic** [comment]
should I make a pull request there or just add everything from there here?

**Comment by owl4ce** [comment]
I think, wait for the PR of @Genghius has passed the test. Then you can fork again after that's PR merged 🤔

**Comment by BeyondMagic** [comment]
I'll follow the second, that'll be easier for mainteiners, I think.

#39 should be merged first and then this one to add only the weather support.

**Comment by owl4ce** [comment]
but https://github.com/Bugswriter/tuxi/pull/39 wants to be merged to the `Bugswriter:develop` branch

**Comment by BeyondMagic** [comment]
hmmm, damn

then there's no problem merging this into the `main` branch at all, right? or should I close this and make a `PR` to `Bugswriter:develop` with it to be tested along the #39??

**Comment by Genghius** [comment]
i would recomend merging to developing branch, and let bugswriter pass it to main once he checks it all works after running trough the tests togetger with #39 . We should start PR'ing to the developing branch so that when we break stuff we dont need to instantly roll back.

**Comment by owl4ce** [comment]
1. Yes, it doesn't matter if this PR is merged into the main branch (current one)
2. By this means there is no google translate feature
3. > I'll follow the second, that'll be easier for mainteiners, I think.
    > 
    > #39 should be merged first and then this one to add only the weather support.

**Comment by Genghius** [comment]
I think the changes made to `translation()` block may break. I recommend leaving it as is and just adding weather block.

**Comment by Bugswriter** [comment]
Why this issue is closed? we still don't have whether.

**Comment by Genghius** [comment]
He closed it so that you didn't merge it yet, as it conflicts with 39. He wanted to wait until 39 was merged so he could rewrite this.
This one can be merged later

**Comment by Genghius** [comment]
However, #44 seems ready, it just needs to have some variable names changed so it can fit.

**Pull request closed without merging**
