### PR TITLE
Dev2

### PR DESCRIPTION
**Pull request by Bugswriter**
Merging and deleting dev2.
Dev2 is almost similar to main
the only different is It have some new working feature of weather added by @Genghius @jhagas

### CODE REVIEW

**Comment by Bugswriter** [comment]
@Genghius I am about to merge dev2 into main since dev2 have ..working weather feature.
But I see you did some changes in makefile 

image

Why this? many users don't have .local/bin ??

**Comment by Genghius** [comment]
> @Genghius I am about to merge dev2 into main since dev2 have ..working weather feature.
> But I see you did some changes in makefile
> 
> image
> 
> Why this? many users don't have .local/bin ??

it's so that installing doesn't need to be run with sudo. However, if you prefer, you can leave it at `/usr/local`...

Btw, I will start to just make my PR's directly to main if I'm sure they work just fine.

**Comment by sudocanttype** [comment]
Could you also merge in #110? It works perfectly well, and without it (on my pc at least), I can't get lyrics. Look at #76 for the details.

**Comment by Genghius** [comment]
> Could you also merge in #110? It works perfectly well, and without it (on my pc at least), I can't get lyrics. Look at #76 for the details.

this would go well in develop branch

**Comment by Bugswriter** [comment]
But dev branch was messy?

**Comment by Genghius** [comment]
> But dev branch was messy?
> You said it before.

I meant `dev2`
my bad I wasnt clear.

**Comment by sudocanttype** [comment]
Yep, the pr is trying to merge into dev2

**Comment by Bugswriter** [comment]
ok listen guys. .. @sudocanttype fixes the .. lyrics related issue and .. @Genghius you enhanced the weather feature. 
So I merged weather feature in dev2. Now it's If I merge lyrics feature? IG this is no issue ? right? 
Dev2 will be ahead of two features from main and we can ..continue with this thread of merging dev2 with main and deleting dev2 making things simple.

**Comment by sudocanttype** [comment]
Yep, the lyrics commit shouldn't mess anything up. The quality test fully passed. We can introduce features in dev2, test them, and if it fully works and doesn't introduce new bugs, we can merge dev2 and main

**Comment by Bugswriter** [comment]
so I merged your PR @sudocanttype ..so now dev2 have fixed version of lyrics and ..better weather view. 
.. 
I am testing things. If you can please try doing some testing on dev2 
@Genghius you too. 
After few ours I will merge dev2 to main, delete dev2 and close this thread. 
Will see other things after that.

**Comment by sudocanttype** [comment]
Ok, I'm going to write a couple more testcases to make sure everything is stable

**Comment by sudocanttype** [comment]
Ok, I added a bunch more quality tests, and all of them passed perfectly (in US). I'm going to create a PR with the new quality test, so if you want to test if it works in india, go ahead.

**Comment by Bugswriter** [comment]
@sudocanttype So I ran all the test . you added in qualitytestscript. This is first time I used test script. 
I must say ..we can make better testscript ..by just doing few change. The first is adding `-r` So I can open testoutput in vim.
Second attaching test query with result. But that is the story of different day.
All tests passed except line 58 -> "Vais para cascais? em ingles"
But this is not an issue. I am got getting anything from google too. may be because of location or something. 
I guess we can merge our dev2 with main. I was thinking about adding few other features.. like quotation feature. 
Which is very simple to add. But remember that's how we ruin our develop branch. So this time. Lets start small.

**Comment by sudocanttype** [comment]
Yep, lets just go one step at a time so we dont accidentally implement something that completely breaks tuxi.

**Pull request merged**
