### PR TITLE
translation scrapper is smaller

### PR DESCRIPTION
**Pull request by BeyondMagic**
easier to update when Google Search updates.

### CODE REVIEW

**Comment by Genghius** [comment]
did it pass the tests?

**Comment by Genghius** [comment]
nice, merge this.

**Comment by Bugswriter** [comment]
Nice job

**Comment by Genghius** [comment]
This made translation break in a way, sometimes returning unrelated content, im reverting this in my next PR.

**Comment by colonvirus** [comment]
@Genghius
`pup 'pre.XcVN5d json{}' | jq -r '[.[] | .children | .[] | select(.class!="BCGytf")][1] | .text' | sed 's/null//g'`

What does `class!="BCGytf"` prevent ?

and why is it better than
`pup 'pre.XcVN5d span:first-child json{}' | jq -r '.[1] | .text' | sed 's/null//g'`?

**Pull request merged**
