### PR TITLE
added "Learn to pronounce" scraper

### PR DESCRIPTION
**Pull request by sdushantha**
This PR is the same as the one in #148, but the branch is set to `main` instead of `develop` in this one.

### CODE REVIEW

**Comment by BeyondMagic** [comment]
@Bugswriter this merged wrongly, this shouldn't call the function `snipcall` with the output of a scrapping, the scrapping should happen in the `snipcall` itself, like the others commands, it's different than the `develop` branch. 

I'd recommend rollback or a new PR by @sdushantha to fix it.

**Comment by Bugswriter** [comment]
Is tuxi is broken? I am on my phone right now? 
If no I ll do it tomorrow.

**Comment by BeyondMagic** [comment]
I can make an PR ready to merge just to fix.

**Comment by Bugswriter** [comment]
tomorrow then

**Pull request merged**
