### PR TITLE
Added units and currency conversion

### PR DESCRIPTION
**Pull request by karthink**
Added support for currencies and scientific unit conversions.
```
$ ./tuxi -r USD 100 to GBP
72.12

$ ./tuxi -r 3 atm in psi
44.0878

$ ./tuxi -r 1.4 GiB to MB
1503.24

$ ./tuxi -r usd 64 to inr
4,655.64
```

### CODE REVIEW

**Comment by Genghius** [comment]
will this merge with #39 without issues?

**Comment by Genghius** [comment]
wont, but all it takes is just renaming 2 variables.

**Comment by Bugswriter** [comment]
Can you tell me what variables I need to change for this merge?

**Comment by Genghius** [comment]
as is at this moment, this PR will try to merge to main instead of development, and it is aiming for the old version (before #39)
image
What can be done, is copy these 2 blocks, rename;
Res6 -> Unit
Res7 -> Currency
and then add to development.

**Comment by Bugswriter** [comment]
What should be the priority?

**Comment by Genghius** [comment]
> What should be the priority?

Units first i believe

**Comment by Bugswriter** [comment]
No I mean ..I should add both in last ?

**Comment by Genghius** [comment]
put them both in between Translate and Knowledge graph

**Comment by Bugswriter** [comment]
I added in last  https://github.com/Bugswriter/tuxi/commit/8fb007da1c543f8613831a012098798605953a9f 
. but it doesn't seem to working 
You should take a look at current tuxi version in develop branch?

**Comment by Genghius** [comment]
i will make a new PR that includes #39, this and a fixed version o #40
Give me a few minutes

**Comment by Bugswriter** [comment]
alright.

**Comment by karthink** [comment]
> I added in last [8fb007d](https://github.com/Bugswriter/tuxi/commit/8fb007da1c543f8613831a012098798605953a9f)
> . but it doesn't seem to working
> You should take a look at current tuxi version in develop branch?

It works once you change `$webpage` to `"$google_html` in the newly added lines (Units and currency)

**Comment by Genghius** [comment]
> > I added in last [8fb007d](https://github.com/Bugswriter/tuxi/commit/8fb007da1c543f8613831a012098798605953a9f)
> > . but it doesn't seem to working
> > You should take a look at current tuxi version in develop branch?
> 
> It works once you change `$webpage` to `"$google_html` in the newly added lines (Units and currency)

nope, strip cant take the numeri values alone. it'll error.

**Comment by Genghius** [comment]
nevermind, the issue is that strip was replaced with output. We really need to stop renaming functions XD

**Comment by Genghius** [comment]
The changes proposed here have already been added by #48 so this PR can be closed.

**Comment by Bugswriter** [comment]
This has been fixed. Working like charm on current develop branch. Closing

**Pull request closed without merging**
