### PR TITLE
Added a makefile

### PR DESCRIPTION
**Pull request by Genghius**
Doing `make` is much easier than doing `cp tuxi ~/.local/bin`

### CODE REVIEW

**Comment by owl4ce** [comment]
> Doing `make` is much easier than doing `cp tuxi ~/.local/bin`

> Doing `make` is much easier than doing `cp tuxi ~/.local/bin`

I just do one command
```bash
$ curl -sL "https://raw.githubusercontent.com/Bugswriter/tuxi/main/tuxi" -o $HOME/.local/bin/tuxi
```

**execute** permissions not needed if previously had that permissions.

**Comment by Genghius** [comment]
good point, imma leave the make file tho. Makefiles make everything better! :turtle:

**Comment by Genghius** [comment]
btw, google translate call should be the last as it seems to be slower than the other for some reason.

**Comment by owl4ce** [comment]
also btw, can you change the usage part of README according to tuxi's output?

**Comment by Genghius** [comment]
> also btw, can you change the usage part of README according to tuxi's output?

sure!

**Comment by owl4ce** [comment]
`--help` arguments is different
```sh
Usage: tuxi [options] query

Options:
  -h                    Show this help message and exit.
  -r                    Raw search results.
                        (no pretty output, no colors)
  -q                    Only output search results.
                        (silences "Did you mean?", greeting, usage)

Report bugs at https://github.com/Bugswriter/tuxi/issues
```

**Comment by Genghius** [comment]
> `--help` arguments is different
> 
> ```shell
> Usage: tuxi [options] query
> 
> Options:
>   -h                    Show this help message and exit.
>   -r                    Raw search results.
>                         (no pretty output, no colors)
>   -q                    Only output search results.
>                         (silences "Did you mean?", greeting, usage)
> 
> Report bugs at https://github.com/Bugswriter/tuxi/issues
> ```

I see, accidentally overlooked it.

**Comment by Genghius** [comment]
wait, no. i dont get what you meant?

**Comment by Genghius** [comment]
image
Here, the null return for translation is fixed so paragraph answers will no longer return null.
The readme has been expanded.
Makefile has been added.

**Comment by owl4ce** [comment]
Now worked like a charm! 🎉

**Comment by owl4ce** [comment]
> wait, no. i dont get what you meant?

`--help` argument between README and tuxi is still different.

**Comment by Genghius** [comment]
> Now worked like a charm!

I still don't get what you wanted me to change in the `--help` option?

**Comment by owl4ce** [comment]
> > Now worked like a charm!
> 
> I still don't get what you wanted me to change in the `--help` option?

Yes it should be in the README, an example of using `--help` brings up like this

image

**Comment by Genghius** [comment]
> > > Now worked like a charm!
> > 
> > 
> > I still don't get what you wanted me to change in the `--help` option?
> 
> No, it should be in the README, an example of using `--help` brings up like this
> 
> image
> 
> https://github.com/Bugswriter/tuxi/pull/37/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R45-R55

`--help` is not a working option for the script tho.
image

**Comment by Genghius** [comment]
Ok, I guess this PR is ready to be merged.

**Comment by owl4ce** [comment]
Dude, I mean, `--help` in README should be replaced to `-h`. Also the output

from
```sh
$ tuxi --help
Usage: tuxi <your question>
       tuxi <OPTIONS> <your question>
OPTIONS:
-r, --raw             Simplify Tuxi output. Useful for e.g notify-send.
-h, --help            Displays this help message.
Report bugs to https://github.com/Bugswriter/tuxi
```
to

```sh
Usage: tuxi [options] query

Options:
  -h                    Show this help message and exit.
  -r                    Raw search results.
                        (no pretty output, no colors)
  -q                    Only output search results.
                        (silences "Did you mean?", greeting, usage)

Report bugs at https://github.com/Bugswriter/tuxi/issues
```

**Comment by Genghius** [comment]
> Dude, I mean, `--help` in **README** should be replaced to `-h`. Also the output
> 
> from
> 
> ```shell
> $ tuxi --help
> Usage: tuxi <your question>
>        tuxi <OPTIONS> <your question>
> OPTIONS:
> -r, --raw             Simplify Tuxi output. Useful for e.g notify-send.
> -h, --help            Displays this help message.
> Report bugs to https://github.com/Bugswriter/tuxi
> ```
> 
> to
> 
> ```shell
> Usage: tuxi [options] query
> 
> Options:
>   -h                    Show this help message and exit.
>   -r                    Raw search results.
>                         (no pretty output, no colors)
>   -q                    Only output search results.
>                         (silences "Did you mean?", greeting, usage)
> 
> Report bugs at https://github.com/Bugswriter/tuxi/issues
> ```
> 
> Next, this PR is ready to be merged.

BRUUUHHHH xd, im blind. didnt see that.

**Comment by Genghius** [comment]
DONE
xd, now this one is 100% ready.
(in theory)

**Comment by Bugswriter** [comment]
So I resolved some conflicts about to merge now.

**Comment by Genghius** [comment]
NICE

**Comment by Bugswriter** [comment]
Not nice. Again broke.

**Comment by owl4ce** [comment]
One careless little thing

image

but in the README

image

**Comment by Bugswriter** [comment]
I don't understand what the hell is happening.
I am keep getting - 
./tuxi: line 84: [: =: unary operator expected
./tuxi: line 141: error_msg: command not found
..even I try to revert to my old working copy of tuxi

**Comment by owl4ce** [comment]
I think it shouldn't really change the function or add to make it more complicated. the old one is good

**Comment by Bugswriter** [comment]
UGGGHHHH .. It was because of cache. Why I am using stupid browser. Guys. .Listen. After this merge I got 
- These errors ->
 /tuxi: line 84: [: =: unary operator expected
./tuxi: line 141: error_msg: command not found

So I reverted everything back to old working copy I had. I tried reverting to the commit @officialcactar  mentioned but Since I was using browser. I thought It's also broken and I reverted back to the copy I am using in my PC. (After Lyrics merge).

**Comment by Genghius** [comment]
image
error_msg should be defined in line 35
image
line 84 should not have any [ nor need for unary operator. It should be just a call to exit 0.

**Comment by Bugswriter** [comment]
I think we should prepare all these new stuff in develop branch. I am going for a 8 hour sleep. You guys can work on this by taking your time.

**Comment by owl4ce** [comment]
**Hi @Bugswriter**
That's a good idea.
Can you return the README and tuxi to this fork? It's the most stable in my opinion in the order of PR. https://github.com/colonvirus/tuxi

**Comment by owl4ce** [comment]
I gathered some information regarding the old stable files.

Tuxi from @colonvirus PR https://github.com/Bugswriter/tuxi/pull/26
**RAW:** https://raw.githubusercontent.com/colonvirus/tuxi/0adbc4105f5f053075e355ced30739a0a0df264a/tuxi

But a new feature added since @Genghius PR Google translation https://github.com/Bugswriter/tuxi/pull/31

**Comment by Genghius** [comment]
All this breaking has been happening because of my mistake with translation returning "null" and the fixes we'vet put arround it while git gets us confused. I made a new pr to development branch. that pr has all of the problems fixed and a script to test if everything is qorking in future changes. Good nigth everyone.

**Comment by owl4ce** [comment]
Ah, yes. At UTC+7 now morning 👍🏻

**Comment by Genghius** [comment]
Gmt 0, here ti's 2am  XD

**Pull request merged**
