### PR TITLE
Added support for lyrics

### PR DESCRIPTION
**Pull request by d-shaun**
Added support for lyrics. This isn't exactly fit for the "Get answers of your questions instantly" description, so I won't mind if this PR gets rejected. 

```
$ tuxi gecgecgec lyrics
---
Back once again
Gec, gec, gec, gec, gec, gec, gec, gec
Gec, gec, gec, gec, gec, gec, gec, gec
Gec, gec, gec, gec, gec, gec, gec, gec
Gec, gec, gec, gec, gec, gec, gec, gec
[...]
```

### CODE REVIEW

**Comment by Bugswriter** [comment]
Cool .. Merging. but first remove those extra tabs. You put before echo on line 6, 14, 19.

**Comment by d-shaun** [comment]
Ah, that was Code's format on save. Reverted now.

**Comment by colonvirus** [comment]
The snippet is different for many other songs, so this isn't complete
`tuxi "the less i know better lyrics"`
> No Result!
`tuxi "funny thing lyrics"`
> No Result!

This is for gecgecgec:


This is for funny thing:

**Comment by colonvirus** [comment]
div class for the second one: PZPZlf

**Comment by owl4ce** [comment]
Mine, VPN connected to Singapore
2021-02-18-021047_1366x768_scrot

**Comment by colonvirus** [comment]
Yea, it works with a VPN connected to Singapore.
Doesn't work in connect to the US.

**Comment by d-shaun** [comment]
I can't seem to be able to reproduce the issue with (/without) a VPN connected to the US (as I live in the US.)
image

**Comment by Bugswriter** [comment]
So are you guys saying lyrics support/feature depends on the country?

**Pull request merged**
