### PR TITLE
✨ added the ability to fetch diseases

### PR DESCRIPTION
**Pull request by PoseidonCoder**
image

### CODE REVIEW

**Comment by Bugswriter** [comment]
cool but top priority for disease? 
It means tuxi will look for disease first before anything? 
We need to decide disease priority. lets just hold this for a moment. since we are dealing with bugs in existing feature. 
First we will fix those then we will think about adding new features.

**Comment by Genghius** [comment]
tuxi already pics of the kno_rigth of diseases.
image
but when i google the disease i cannot find the text that youa re refering to https://user-images.githubusercontent.com/34260118/108437805-dc82e900-7202-11eb-9c7b-68dae122797a.png <- here, how is this text being scrapped?

**Comment by PoseidonCoder** [comment]
image
It scrapes the list under the text where it says "Rare"

**Comment by PoseidonCoder** [comment]
image
It'll know just scrape the description

image

**Pull request closed without merging**
