### PR TITLE
Lyrics weren't working (US), made them work again. Added back gitignore. 

### PR DESCRIPTION
**Pull request by sudocanttype**
If you want. just ignore all the changes but the tuxi file changes. All the others aren't super important

### CODE REVIEW

**Comment by Bugswriter** [comment]
What is this PR? Where are you getting issue in dev2? 
Also is this the issue in `main` too?

**Comment by colonvirus** [comment]
You don't need to add another one
Replace
`pup 'div.bbVIQb text{}'`
with
`pup 'div.ujudUb text{}'`

**Comment by sudocanttype** [comment]
Yep, it's the same bug that was fixed in #76. For some reason, we have different divs for lyrics in the US. 

> You don't need to add another one
> Replace
> `pup 'div.bbVIQb text{}'`
> with
> `pup 'div.ujudUb text{}'`

I didnt want to tinker with already existing code, as it could (as it has before) completely break tuxi.

**Comment by sudocanttype** [comment]
Yep, this issue is also in main.

**Comment by BeyondMagic** [comment]
```bash
    printf "  -a                    Use all snippets.\n"
    printf "  -l                    Print location after snippet call.\n"
```
Documentation for the options in "tuxi -h". 8

**Comment by sudocanttype** [comment]
This isnt a new option, its just that lyrics is placed in a different div in the US. Its a bugfix.

**Comment by sudocanttype** [comment]
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6015410/testoutputs.txt)
Test output with more lyric testing. I pulled the songs at random from the top 50 2020 song list and some other random songs.

**Pull request merged**
