### PR TITLE
make time now work

### PR DESCRIPTION
**Pull request by sudocanttype**

### CODE REVIEW

**Comment by owl4ce** [comment]
I use `main` branch version, and it's just works.
image

**Comment by owl4ce** [comment]
Where are the `recd` dependencies? I haven't found it yet.

**Comment by Bugswriter** [comment]
The issue was in develop branch not on main. Should I merge this? are we ready? @sudocanttype

**Comment by owl4ce** [comment]
Oh sorry, it's a function, I'm not careful.

> I want to try devel branch. Where are the `recd` dependencies? I haven't found it yet.

**Comment by Bugswriter** [comment]
@sudocanttype 

image

**Pull request merged**
