### PR TITLE
Panacea 3, I give up!

### PR DESCRIPTION
**Pull request by Genghius**
This thing has reached the point where its a snowflake in the middle of a desert, if i touch anything im afraid it'll fall appart.
thus I give up on trying fixing any more than this.
-Makefile has been reverted, it should have always pointed towards `~/.local` not `/usr/local` considering this is a script.
-fixes issue #103 

... That is, by reverting the PR that made translate faster
image
And sending rich lists to the bottom of the script...
image
turns out... rich lists are all the world's evil.
-From now onwards, all changes in the order of the scraps will need to have an explanation / reason.
image

Code is getting messy, complex and un-extensible (rich lists being th egreatest contributor to this).
I advise for putting every scrap into its own function, getting rid of any scrap that will read more than 1 html element and having much stricter testing on anything added by new PR's.

### CODE REVIEW

**Comment by Genghius** [comment]
This PR accidentally tries to change the README.md file. However, it just brings it to an older version, if this is to be merged, README should be ignored.

**Comment by Genghius** [comment]
***This pr has not been run trough any test, and I leave this to yall, caus i truly have no idea what i have done or if it'll work.***

**Comment by Genghius** [comment]
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6010219/testoutputs.txt)
my testoutputs.txt file.
image
basic tests.

**Comment by Bugswriter** [comment]
Our main branch currently is working pretty nicely. 
The goal is our tuxi should do all the features We have properly. 
How about .. making a backup of our current develop branch and deleting it?
Then start with start with main again. 
First we will turn everything into functions .. properly and .. merge it with main.
then We will start adding features we have in our current develop branch?

**Comment by Genghius** [comment]
> Our main branch currently is working pretty nicely.
> The goal is our tuxi should do all the features it offer.
> How about .. making a backup of our current develop branch and deleting it?
> Then start with start with main again.
> First we will turn everything into functions .. properly and .. merge it with main.
> then We will start adding features we have in our current develop branch?

that seems to be the best option, because everything in develop is messy.

**Comment by Bugswriter** [comment]
> 
> 
> _**This pr has not been run trough any proper test, and I leave this to yall, caus i truly have no idea what i have done or if it'll work.**_

I understand the frustration. I also believe this thing is getting too fragile. That's why. I am suggesting to just forget about our current develop branch and start with making functions in main branch and ..TEST THE HELL OUT OF IT.

**Comment by Genghius** [comment]
> > _**This pr has not been run trough any proper test, and I leave this to yall, caus i truly have no idea what i have done or if it'll work.**_
> 
> I understand the frustration. I also believe this thing is getting too fragile. That's why. I am suggesting to just forget about our current develop branch and start with making functions in main branch and ..TEST THE HELL OUT OF IT.

imma do that.

**Comment by Bugswriter** [comment]
So I created the dev2 branch and I think instead of adding new feature first .. lets organize everything which we have. 
By creating functions we are not altering anything so there is no chance of break (if we do things properly)
After this we can test 
and then look into out messy branch to steal features which are not getting any issues.

**Comment by Bugswriter** [comment]
> imma do that.

Opps I wrote main. don't do anything in main. I made dev2 branch (fork of main)

**Comment by colonvirus** [comment]
Imma take on documenting all of google's SERPs, and their html, location differences, so other devs can understand how each SERP is scraped, and not just go "hmm yeah that seems cool, add it", which was how we got to this point.

**Pull request closed without merging**
