### PR TITLE
Added basic support for rich list

### PR DESCRIPTION
**Pull request by d-shaun**
This could be improved to make the list look more elegant but trying to `jq` the JSON wasn't a very pleasing experience, so I decided resort to this basic implementation.

```
$ tuxi game of thrones s03 episodes
---
S03 E10 · Mhysa
Jun 9, 2013
S03 E09 · The Rains of Castamere
Jun 2, 2013
S03 E08 · Second Sons
May 19, 2013
S03 E07 · The Bear and the Maiden Fair
May 12, 2013
[...]
```

```
$ tuxi elephant height
---
African bush elephant: 3.2 m
Asian elephant: 2.8 m
---
```

### CODE REVIEW

**Comment by Genghius** [comment]
seems nice, can you send me your `testoutputs.txt` file?

**Comment by Bugswriter** [comment]
This is cool but we need to test this properly. Also this is just .. going to add stuff right? Not changing anything which already exist? I just want to know ..adding this code ..is only going to benefit us?

**Comment by Genghius** [comment]
imma test this. gimme a minute.

**Comment by Genghius** [comment]
mhhh, i cant test it, lets wait for PR'r to send test outputs

**Comment by d-shaun** [comment]
> Also this is just .. going to add stuff right?

Yup.
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6005076/testoutputs.txt)

The `testoutputs.txt` is painful to look at and the lack of the corresponding test names makes it worse, but I was thrown off by this ((warning)):
> Please do not try to make this script any more fancy or extensible, just leave it as is.

**Comment by Bugswriter** [comment]
@d-shaun are you saying there is a issue in tuxiqualitytest.sh? if yes then can you do manual testing and tell me .. Is your PR is ready to go?

**Comment by d-shaun** [comment]
No, wait. It seems to have broken the weather thing.

**Comment by colonvirus** [comment]
could you rename the variable to `rich_list`?

**Comment by d-shaun** [comment]
Sure thing

**Comment by d-shaun** [comment]
I'm placing this after weather and before the "knowledge graph." I'll see how that goes.

**Comment by d-shaun** [comment]
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6005175/testoutputs.txt)
OK, everything works. 
@Bugswriter: Ready to be merged.

**Comment by Genghius** [comment]
> > Also this is just .. going to add stuff right?
> 
> Yup.
> [testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6005076/testoutputs.txt)
> 
> The `testoutputs.txt` is painful to look at and the lack of the corresponding test names makes it worse, but I was thrown off by this ((warning)):
> 
> > Please do not try to make this script any more fancy or extensible, just leave it as is.

the warning was put by me, what it actually means is "Dont change the test script without testing that it works properly."

**Comment by Bugswriter** [comment]
> [testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6005175/testoutputs.txt)
> OK, everything works.
> @Bugswriter: Ready to be merged.

Sure?

**Comment by d-shaun** [comment]
Yup. We'll probably have to reorganize the priority  because #85, but I guess it's better to have a separate PR for that after this is merged.

**Comment by Bugswriter** [comment]
Yeah cool. Merging.

**Comment by Bugswriter** [comment]
Getting a bit distorted output ? do you why this is happening?
image

**Comment by Bugswriter** [comment]
image

Look like it's googles fault. I guess adding one line space between each list item would be better.

**Pull request merged**
