### PR TITLE
Human readable

### PR DESCRIPTION
**Pull request by Genghius**
The function to check dependencies would be better with just a loop that checks if every argument is an installed package.
Also, one-liners with `&&` and `||` should be avoided outside of conditionals.

UwU
I use arch btw.
ARCHBTW

### CODE REVIEW

**Comment by owl4ce** [comment]
BTW, `utf-8` should be `ISO-8859-1` and .. actually not about **human readable**, but previously followed philosophy of suckless.

**Comment by Bugswriter** [comment]
I did changed this with a merge.

**Comment by Genghius** [comment]
Didnt realize, i forked this this morning before the other PR was merged.

> BTW, `utf-8` should be `ISO-8859-1` and .. actually not about **human readable**, but previously followed philosophy of suckless.

**Comment by Bugswriter** [comment]
Why you closed the pull request. You did good job .. making code cleaner .. ?? All you had to do just revert that changed with utf8 .

**Comment by Genghius** [comment]
oh? i thought the code was already cleaner with the other PR

**Comment by Bugswriter** [comment]
But since you forked it in morning .. can you revert those iso -> utf8 ? Also cross check things so I can merge?

**Comment by Genghius** [comment]
image
seems to not be broken.

**Comment by Bugswriter** [comment]
Awesome .. good job. Thanks.

**Comment by colonvirus** [comment]
Imma try make the code more cleaner and readable, and with comments for each of the google snippets.

**Comment by colonvirus** [comment]
> BTW, `utf-8` should be `ISO-8859-1` and .. actually not about **human readable**, but previously followed philosophy of suckless.

> 

> Most hackers actually don't care much about code quality. Thus, if they get something working which seems to solve a problem, they stick with it. If this kind of software development is applied to the same source code throughout its entire life-cycle, we're left with large amounts of code, a totally screwed code structure, and a flawed system design. This is because of a lack of conceptual clarity and integrity in the development process.
> \- suckless.org

I would say being human readable is important

**Pull request merged**
