### PR TITLE
Fixed translation and snippet "View all" bug, added a chemistry thing

### PR DESCRIPTION
**Pull request by sudocanttype**
Also added a gitignore so I don't accidentally upload the quality test output

### CODE REVIEW

**Comment by BeyondMagic** [comment]
To make things easier, please add the options -a and -l into `tuxi` -h option

```bash
    printf "  -a                    Use all snippets.\n"
    printf "  -l                    Print location after snippet call.\n"
```

**Comment by sudocanttype** [comment]
In theory this should close #93. Also what is the point of 

> To make things easier, please add the options -a and -l into `tuxi` -h option
> 
> ```shell
>     printf "  -a                    Use all snippets.\n"
>     printf "  -l                    Print location after snippet call.\n"
> ```
I'm confused, how does this make things easier?

**Comment by BeyondMagic** [comment]
Instead of a pull request only to add the options that are left to be documented in the `tuxi` help, you can add those right now, but if you don't want to, there's no problem.

**Comment by sudocanttype** [comment]
Oh, sorry. I don't think I can edit the pull request after it has been submitted, but next time I'm implementing a change I'll also add it to the help.

**Comment by BeyondMagic** [comment]
It's once it's merged, you can commit to your repository and git will update the pull request here automatically.

**Comment by Bugswriter** [comment]
I am merging this without testing? Is this ready?

**Comment by Bugswriter** [comment]
Also what's chem thing? I try not to add more feature Until we fix all our issue, test properly and create functions for each feature.

**Comment by sudocanttype** [comment]
It works perfectly fine for me, so I'd say yes. here's the testoutput. No errors or anything out of the ordinary
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6008020/testoutputs.txt)

**Comment by Bugswriter** [comment]
ok merging.

**Comment by sudocanttype** [comment]
Ah I added that before I saw that we were avoiding adding new features my bad

**Comment by Bugswriter** [comment]
Keep in mind now. Good job.

**Pull request merged**
