### PR TITLE
PR, make develop the same as main.

### PR DESCRIPTION
**Pull request by Genghius**
also removes a few extra lines in tuxiqualitytest.sh

### CODE REVIEW

**Comment by Genghius** [comment]
In case it wasnt clear, -Thisreverts develop to what main is rn.

**Comment by Bugswriter** [comment]
umm why not using dev2 ? 
I think we should leave this branch as it is. since This branch have lot of cool features?

**Comment by colonvirus** [comment]
How about moving develop's stuff over to dev2, and develop reverts to main?
develop is a better name lol

**Comment by colonvirus** [comment]
:(

**Comment by Bugswriter** [comment]
> 
> 
> How about moving develop's stuff over to dev2, and develop reverts to main?
> develop is a better name lol
LOL hell no
dev2 is fresh fork of main
Why doing all this? just for name.

**Comment by colonvirus** [comment]
Naming is good

**Comment by Bugswriter** [comment]
> Naming is good
> When people see "develop", they think "yea, that's where the new version is being made"
> "dev2" seems kinda meh
> We could have develop and develop-backup instead

Lets do this for few hours and once we done with our functions I ll merge and delete dev2.

**Comment by Genghius** [comment]
> > How about moving develop's stuff over to dev2, and develop reverts to main?
> > develop is a better name lol
> 
> LOL hell no
> dev2 is fresh fork of main
> Why doing all this? just for name.

oh, i see. i got it th eother way arround, thougth develop would be main and dev2 develop

**Pull request closed without merging**
