### PR TITLE
Purert version, Are we ready?

### PR DESCRIPTION
**Pull request by Bugswriter**
I am just opening this PR. 
Since @PureArtisty version is better .. a lot better actually. We should now just get rid of our current main. 
All I want to know is it's not going to break right?
Chill I am not going to torture you if it broke.
I just want you opinion.

### CODE REVIEW

**Comment by BeyondMagic** [comment]
It's not ready and the merge will need to be forced.

**Comment by PureArtistry** [comment]
I'm mot sure if it's quite ready for main, needs more testing to get the priority right, it works differently from main and we need to make sure it's popping out the correct answers first

also the micro delay needs testing on more different machines to get a good default where it's unlikely to spit out more than one answer

might be other stuff but I'm confident it's not broken in any way or has major bugs
as for merging, as @BeyondMagic said, it's not going to be clean.

also before swapping over it would be good to update the docs, readme etc for the new version

**Comment by Bugswriter** [comment]
Ok I will hold this then.

**Comment by Genghius** [comment]
Panacea 5, "the last stand". Confirmed by Genghis coming in 2025.

**Comment by BeyondMagic** [comment]
@PureArtistry you changed back the `math` to a new space before the result? Aw

**Comment by BeyondMagic** [comment]
@PureArtistry the query "the office cast" is having conflicts, can you try it?

**Comment by PureArtistry** [comment]
I'll take a look at it, then I'm going to go over the define snippet as the output of that is a bit messy

the rich snippet needs altering, it was tweaked to improve it's performance in the main script but that is not really needed for mine, I can stick each of the things it checks into their own functions and get rid of the cast list scrape that was in there for just the richcast one and list one

**Comment by BeyondMagic** [comment]
Using -a it prints around ~4 answers I think, the last one is the correct, I can't test it right now, but it's definitely a problem with priority and scrapping, I believe many tried to rework on that, including me, on the main, but it's not that simple.

**Comment by PureArtistry** [comment]
yeah I'll take a look at that next

**Comment by BeyondMagic** [comment]
Back, richcast is definitely the one for `social network cast` and type-like queries. I think it doesn't have any conflicts with any of the others (its scrapping seems to be unique on Google Search UI).

**Comment by Bugswriter** [comment]
@PureArtistry dude I think you should first work on this.. Many people are asking for new features .. we have so many good ideas. Once we merge this PR I will delete. All other branches and make a new branch develop. Then You and all other devs will work on that develop branch. Things will get less messy.

**Comment by PureArtistry** [comment]
sorry, was busy yesterday.

I'm currently working on getting this ready for main today, just done one commit.
Im about to go through the testqueries.txt to make sure we are looking for the right results for each query, after I have finished that and uploaded the new version, I''m going to need some people to test the latest version and send me the results

**Comment by PureArtistry** [comment]
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6090932/testoutputs.txt)

it's looking good to me, the only 2 fails in the tests are a weather one (which is a google problem and nothing to do with the script) and a fail caused by a bug in the main script that only effects the debug output (it doesn't show what answer was selected, this is low priority right now)

I'm going to fiddle with the help menu do make it a little more readable and then have a look at the define snippet and see if I can line up the definitions with their type

**Comment by Bugswriter** [comment]
So are we ready?

**Comment by PureArtistry** [comment]
nearly finished with define snippet ajustments, need another hour (ish) - then as long as it's working for other people I would say it's ready

I will @ you in the PR (#167) when I'm done, then you can merge that and we can do a couple of final tests

**Comment by PureArtistry** [comment]
small hitch, it works great when there are multiple definitions but the format is messed up if there is only one (should have tested a couple more words to notice that)

It's going to be a little bit longer

**Comment by PureArtistry** [comment]
@Bugswriter 
I'm happy with the way my version is running now, unless anybody wants to test the lastest version on my fork and finds any bugs, I think as soon as docs are updated and you've decided how you want to handle the conflicts this is ready.

**Comment by Bugswriter** [comment]
I will test this today and .. give a review. 
I think it's time we are ready to merge this and close this issue. 
Awesome job @PureArtistry

**Comment by PureArtistry** [comment]
I'm going to get some food and then carry on with the sports fixture snippet I started and fix it for sports other than football, there's a chance I could have that ready in a couple of hours

**Comment by PureArtistry** [comment]
@Bugswriter - aside from bug fixes (if needed), I'm done fiddling with this for now

**Comment by Genghius** [comment]
day 752.
I still have hope that eventually, pureart version will be merged to main.
I hope, therefore I am.

#WaitingForItUwU

**Comment by Genghius** [comment]
> day 752.
> I still have hope that eventually, pureart version will be merged to main.
> I hope, therefore I am.
> 
> #WaitingForItUwU

day 1357.
I have decided I shall rewrite tuxi in c once pureart version is ready.
(Time is measured differently in Genghius units btw.)

**Comment by PureArtistry** [comment]
> > day 752.
> > I still have hope that eventually, pureart version will be merged to main.
> > I hope, therefore I am.
> > #WaitingForItUwU
> 
> day 1357.
> I have decided I shall rewrite tuxi in c once pureart version is ready.
> (Time is measured differently in Genghius units btw.)

funny you say that, I was giving serious consideration to re-writing it (with it's deps) in rust, I've been wanting to learn the language.

**Comment by Bugswriter** [comment]
@Genghius @PureArtistry @BeyondMagic 
I am really sorry I took so long to merge purert-version. I was busy setting up my website bugswriter.com / email suraj@bugswriter.com and some other stuff for my youtube channel. But now I resolved all conflicts and purert-version is in main and I deleted purert-version also I deleted develop and make a new fresh develop branch out of purert-version.
Now I merge purert version but I have some concerns which I want to point out .. This version is currently highly dependent of @PureArtistry .. It's not bad it's just my concerns. I mean .if google change something in CSS it will become hard for us to fix. 
I will now become more active on this project .. Don't lose interest @PureArtistry. 
Thanks a lot for you work. You truly changed this script in a better way. 
also thanks to @BeyondMagic @Genghius and others. for working on this. 
It feels like tuxi is reborn with new stuff <3 from @PureArtistry

**Comment by PureArtistry** [comment]
this version that you have merged is way older than my latest version, did you want me to clone this and send you a pr with all the latest changes?

btw, I won't be losing interest, trust me - even when I get around to the rust version I'll still help maintain this (I love writing shell code) - I think the concept of tuxi is really cool

as far as other people maintain this, I'm happy to explain bits of it or write more comments for stuff if it's needed

**Comment by Bugswriter** [comment]
Oh sorry It was a fresh clocne. . Idk why this happened. You can give pr ofc.

**Pull request merged**
