### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Bugswriter**
So I guess our develop branch is ready with lot of new features like 
- Wheather
- Currency
- Units
Should I merge this to main? You guys added units and currency in tuxitest.sh ?

### CODE REVIEW

**Comment by Genghius** [comment]
yes, the tuxiqualitytest.sh file now tests for currency, weather and units.
Develop is ready to go to main.

**Comment by colonvirus** [comment]
No, we have to fix the readme, add a gif, and tuxiqualitytest.sh's echo doesn't work on mine, so i have to change it to printf

**Comment by colonvirus** [comment]
currency and units arent recoded

**Comment by Bugswriter** [comment]
I fixed the merge conflicts .. We are ready to go. 
But since you guys are having some of you own conflicts XD.
I am on hold.
Should we add GIF before merging with main? Also Please someone fix that AUR OTHER the heading size looks similar to install. Also 'other' is not a good heading for usual way of installing AUR should be on second.

**Comment by colonvirus** [comment]
Im working on fixing readme, and minor stuff on tuxiqualitytest, and tuxi
So yea hold for a while 😃

**Comment by owl4ce** [comment]
I think, README is the last one if all problems have been resolved. Then, just ready to merge to main.

**Comment by colonvirus** [comment]
develop tuxi has currency and units twice too

**Comment by owl4ce** [comment]
> Im working on fixing readme, and minor stuff on tuxiqualitytest, and tuxi
> So yea hold for a while

Maybe you can add a little icon in README.
https://gist.github.com/rxaviers/7360908

**Comment by Bugswriter** [comment]
> develop tuxi has currency and units twice too
> that wouldve been a bug
> so yea, wait

I am fixing this wait.

**Comment by d-shaun** [comment]
Maybe switch to using `printf` instead of `echo` in `tuxiqualitytest.sh`? 
image

**Comment by colonvirus** [comment]
yep, doing that

**Comment by colonvirus** [comment]
#51 lets goo

**Comment by Bugswriter** [comment]
So We will do GIF later?

**Comment by colonvirus** [comment]
One more commit
Yes, gif later

**Comment by Bugswriter** [comment]
awesome job. Tuxi is so much better now. 
In our next merge We will add quotations and GIF in read me.

**Pull request merged**
