### PR TITLE
Better Read Me

### PR DESCRIPTION
**Pull request by owl4ce**

### CODE REVIEW

**Comment by owl4ce** [comment]
@Bugswriter

**Comment by owl4ce** [comment]
Hi guys, it's almost midnight in my region, I'll goes to sleep okay 👍🏻

**Comment by owl4ce** [comment]
It would be better if there was a logo for Tuxi

**Comment by Genghius** [comment]
> It would be better if there was a logo for Tuxi

i propose we just make an ascii tux tuxi's logo.

**Comment by Genghius** [comment]
this readme is good, merge the PR plz.

**Comment by owl4ce** [comment]
Wait for a while. I'll do more updates.

**Comment by Bugswriter** [comment]
> Wait for a while. I'll do more updates.

Opps I merged. Since our current version was not very clean. Also can't we turn this - "Tuxi is a CLI tool that scrapes Google search results and SERPs, and provides instant, concise answers for your questions in the terminal." into a smaller description.

**Pull request merged**
