### PR TITLE
searches for meaning of a word

### PR DESCRIPTION
**Pull request by igaurab**
image

Adds support to search for the meaning of a word.

### CODE REVIEW

**Comment by Genghius** [comment]
does it run `tuxiqualitytest.sh` without errors?

**Comment by Bugswriter** [comment]
wonderful. Tuxi can now be used as dictionary too.

**Comment by Bugswriter** [comment]
> does it run `tuxiqualitytest.sh` without errors?

He didn't added test for this feature. This thing will pass the test?

**Comment by Genghius** [comment]
> > does it run `tuxiqualitytest.sh` without errors?
> 
> He didn't added test for this feature. This thing will give the test?

he doesnt need to add test, i'll do it in the next pr. we just need for all the other tests to pass so that we can be sure nothing is broken.

**Comment by Bugswriter** [comment]
This PR is for main. where develop branch is 13 commits a head. can't merge into main. give a pull request for develop branch.

**Comment by igaurab** [comment]
Regarding the test, it does pass all the test without error, but I have not written test for this particular `define` command support. 

Sure, I'll give a PR for the develop branch

**Comment by Genghius** [comment]
> Regarding the test, it does pass all the test without error, but I have not written test for this particular `define` command support.
> 
> Sure, I'll give a PR for the develop branch

ok, i'll pass a PR in 30 minutes to make develop and main even, i'll also add a test for this.

**Pull request closed without merging**
