### PR TITLE
Language constant

### PR DESCRIPTION
**Pull request by Genghius**
People may want to change the language of their queries, this would allow for it to be much easier.

### CODE REVIEW

**Comment by sudocanttype** [comment]
If you're merging to main, you should definitely document this new feature in the README

**Comment by Genghius** [comment]
> If you're merging to main, you should definitely document this new feature in the README

Sure.

**Comment by Bugswriter** [comment]
Good thought.

**Comment by Genghius** [comment]
Done, the readme has been edited, and now it has fallbacks, if no language is set by the user, it will use the system default, if no system default is found, it'll use `en_US`

**Comment by Bugswriter** [comment]
awesome

**Pull request merged**
