### PR TITLE
Remove degree units from weather output

### LINKED ISSUE #112: Weather outputs flipped for degrees C and F
- `shell` bash
- `Operating system/version`: arch
- `Terminal name/version`: st
- `$TERM`

## Steps to Reproduce the Problem
Run tuxi with weather query: `tuxi weather 10001`

## Expected Behavior
32 ºF
0 ºC

## Actual Behavior
32 ºC
0 ºF

## The Problem
The degrees are flip flopped. I have committed the changes to my fork and will open a PR.

### PR DESCRIPTION
**Pull request by zachspar**
This change takes out the degree units from the weather output, leaving it up to the user to interpret what unit it is. This would technically fix #112, as @Genghius suggested. I wish the US would just use normal units like everyone else.

### CODE REVIEW

**Comment by sudocanttype** [comment]
Heh, the US being normal? not gonna happen. It would technically fix it, but it's not exactly a good fix, as there could be a significant amount of confusion from it

**Comment by BeyondMagic** [comment]
I think the **ID** of Celsius and Fahrenheit are different in Google Search Scrapping, someone from U.S. needs to confirm. It seems that for C it is always **wob_tm** and for F **wob_ttm**.

image

**Comment by zachspar** [comment]
@sudocanttype Celsius is always greater than Fahrenheit, I don't think it is that confusing.

**Comment by sudocanttype** [comment]
@BeyondMagic  Yep, just checked (in us), 
image

**Comment by zachspar** [comment]
No, @sudocanttype your C is `wob_ttm` and @BeyondMagic's C is `wob_tm`

**Comment by sudocanttype** [comment]
Ah, I'm just dumb. Looks like tm is just default for region, which makes this so much harder to code for. Also once again, got confused.

**Comment by zachspar** [comment]
Nobody is dumb lol , confusing stuff

**Comment by BeyondMagic** [comment]
Yep, you're right @sudocanttype, it's better using a simple comparison, is there any one-line way to do that in POSIX?

**Comment by zachspar** [comment]
Closing this PR. Issue #112 is still persistent with a possible solution of comparing the two values with the assumption that C < F always holds true.

**Pull request closed without merging**
