### PR TITLE
big update, see PR for details

### PR DESCRIPTION
**Pull request by PureArtistry**
sorry for the delay with this, got kinda busy...

completely re-worked processing code, no more stupid lock file and no more crashes
added a number of new features and updated help to reflect everything available [ this will fix: #151 #118 #50 implements #137 #87 ]

scrot_20210228-143709

also re-worked test script making it easier to maintain and makes the output easier to parse (more grep friendly)
priority order may need fiddling with, needs some testing to figure out best order
also the testqueries.txt could do with going through and updating

[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6056918/testoutputs.txt)

let me know what you think

### CODE REVIEW

**Comment by Bugswriter** [comment]
I am merging this. can you tell me ..  is your version is capable of doing everything which our current tuxi can do? in main?

**Comment by PureArtistry** [comment]
Ill check the code in main now, give me 10 minutes

**Comment by PureArtistry** [comment]
the only thing missing is #152 
did you want me to add it in and credit or give @sdushantha a chance to send a PR with it in so he gets credited on the blame if he wants to?

**Comment by PureArtistry** [comment]
I'm going to message @sdushantha and give him a file with the changes made, he can just send that back in a PR

**Comment by Bugswriter** [comment]
> the only thing missing is #152
> did you want me to add it in and credit or give @sdushantha a chance to send a PR with it in so he gets credited on the blame if he wants to?

I think. .. if that's the case I should merge your version with main. But we need to do some testing. and make sure it's not going to break.

**Comment by PureArtistry** [comment]
yeah, as I said the priority might need adjusting, also maybe the default TUXI_DELAY - need more people to test it and see if it holds up

trying to figure out the best way to contact @sdushantha, there isn't an email address and I don't have any social media accounts to contact him/her on the ones they've detailed

I have created an updated tuxi script with the required changes they just have to send it back in a PR

**Comment by Bugswriter** [comment]
yeah no need to rush. I am also in busy in my exams.. but I like your work. and will merge it to main .. but only when I get sure by other devs. it's working fine.

**Comment by PureArtistry** [comment]
thanks!

**Comment by sdushantha** [comment]
> the only thing missing is #152
did you want me to add it in and credit or give @sdushantha a chance to send a PR with it in so he gets credited on the blame if he wants to?

@PureArtistry You can go ahead and add it if you want. I am a little busy and don't have much time to work on it

**Comment by PureArtistry** [comment]
@sdushantha - will do thanks.

Also thanks for your font preview script, never seen convert used for that before - I have since used it in a few of my scripts

**Pull request merged**
