### PR TITLE
POSIX compatbilitiy changes.

### PR DESCRIPTION
**Pull request by officialcactar**
I've removed string indexing, made coloring posix-compliant, and removed the non-standard xargs flag.

Testing these changes on OpenBSD, FreeBSD and GNU/Linux. 
This script should also work on MacOS but is untested

### CODE REVIEW

**Comment by owl4ce** [comment]
zsh-bash-sh
image

**Comment by officialcactar** [comment]
> 
> 
> **zsh**-**bash**-**sh**
> GNU/Linux
> 
> image
> 
> image

The "--help" issues are fixed!

**Comment by owl4ce** [comment]
Typo

**R="nvim\033[1;31m";***
```cfg
3 N="\033[0m"; R="nvim\033[1;31m"; G="\033[1;32m"; M="\033[1;35m"; C="\033[1;36m"
```

and also this

image

**Comment by officialcactar** [comment]
all issues should be fixed
image

**Comment by owl4ce** [comment]
> all issues should be fixed
> image

Yeah, now this
1. Diferrences in answer between normal search and raw output, the cause is "-r" or "--raw" included in query?
2. New line for dependencies checking

image

**Comment by officialcactar** [comment]
image

**Comment by owl4ce** [comment]
one left 👍🏻 

2021-02-17-203327_1366x768_scrot

**Comment by Bugswriter** [comment]
nice job. I just merged some functionalities. Can you take a look at current version of tuxi and make sure that you POSIX compatibility update will not change any behavior of program in GNU/Linux system?
Sorry I am very unfamiliar with this thing .. but want to make my program UNIX friendly. 
Also correct me if I wrong after this merge We will resolve - https://github.com/Bugswriter/tuxi/pull/22 ?

**Comment by officialcactar** [comment]
> 
> 
> nice job. I just merged some functionalities. Can you take a look at current version of tuxi and make sure that you POSIX compatibility update will not change any behavior of program in GNU/Linux system?
> Sorry I am very unfamiliar with this thing .. but want to make my program UNIX friendly.

I made a [little script](https://pastebin.com/82JZFSTJ) testing all of the functions and tried it on ubuntu.
image

The output of the functions are identical and I'm currently not aware of anything that would change GNU/Linux behavior.

> Also correct me if I wrong after this merge We will resolve - #22 ?
yes

**Comment by Bugswriter** [comment]
Good job man

**Pull request merged**
