### PR TITLE
implement pureartistry's fix, but for main

### PR DESCRIPTION
**Pull request by sudocanttype**
Lmao half (or like 90%) of this code is pureartistry's. Everything is working, the testoutput is attached. I recommend someone else try and make sure this works before merge. 
<br/>
BTW, this code is supposed to be temporary fix for #112 until purert gets into main, so it should be fine for now.
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6031464/testoutputs.txt)

### CODE REVIEW

**Comment by BeyondMagic** [comment]
@sudocanttype 

There are two translate lines in `tuxi`, could you remove it?

https://github.com/Bugswriter/tuxi/blob/dc714749a563be654b89fb0c3e9a4efbc45b1ec0/tuxi#L210-L216

**Comment by sudocanttype** [comment]
alright

**Comment by sudocanttype** [comment]
Huh never noticed that, I'll delete it

**Comment by Bugswriter** [comment]
Wait .. I am getting PR for main..
Also some people are saying merging @PureArtistry -version with main? 
What's the point of improving main then?

**Comment by sudocanttype** [comment]
this code is supposed to be temporary fix for #112 until purert gets into main, so it should be fine for now.
The PureArtistry version is still being worked on, and I want the bug fixed in main until purert becomes main

**Comment by sudocanttype** [comment]
@Bugswriter There was a bug that was merged in. The learn to pronounce was not tested at all, and it does not work because it was written with the old way of snipcall. I rewrote it to work and added testcases for it. As of this commit everything in this commit should work.
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6046526/testoutputs.txt)

**Comment by BeyondMagic** [comment]
this is pretty much ready to merge @Bugswriter

**Comment by Bugswriter** [comment]
I am middle of my exams .. so I am just merging can't test. All up to you soldiers. Tomorrow I will join.

**Comment by BeyondMagic** [comment]
this didn't change many things, it's working normally
good luck in your exams

**Pull request merged**
