### PR TITLE
Support other languages

### PR DESCRIPTION
**Pull request by Alpakka31**
Fixes encoding without forcing English language #11

### CODE REVIEW

**Comment by Bugswriter** [comment]
But then people will get &amp instead of " ??

**Comment by Alpakka31** [comment]
The latest commit should fix it both issues

**Comment by Bugswriter** [comment]
Some fixed this by forcing english - https://github.com/Bugswriter/tuxi/pull/12
I think it's more cleaner. 
I think it's better if tuxi only answer in English because google answer from websites and most websites are in english.
Other languages support can complicate things lead us to more bugs.

**Comment by Alpakka31** [comment]
I totally agree with you.

**Comment by colonvirus** [comment]
This fixes #15, so I think this should be added

**Comment by colonvirus** [comment]
`recode html..utf8 | iconv -f UTF-8 -t ISO-8859-1`
can be replaced with 
`recode html..ISO-8859-1`

**Pull request closed without merging**
