### PR TITLE
Degoogled the whole script.

### PR DESCRIPTION
**Pull request by spector-9**
I would like if you cancel this request and create a new branch relative to the main and I shall create pull request for that branch. Since there are few things that need to be implemented but I can't do them alone.

### CODE REVIEW

**Comment by BeyondMagic** [comment]
Google still way faster than any other search engine or "port" of it, shouldn't this best putting in your own fork? I believe some people would be glad to use security features from whoogle.

**Comment by Genghius** [comment]
> Google still way faster than any other search engine or "port" of it, shouldn't this best putting in your own fork? I believe some people would be glad to use security features from whoogle.

Whoogle would be way better than google, also, I tested this side by side with normal tuxi and there seems to be no performance issue.

**Comment by Bugswriter** [comment]
But the idea was to use tuxi for getting goodie answers from google without executing adwares.?? 
You can't get answer for "do tattoo bad for skin" in any other search engine.

**Comment by BeyondMagic** [comment]
How many Wgoogle servers have around the world? Maybe the speed is the same
in some countries, but not in mine.

**Pull request closed without merging**
