### PR TITLE
Made weather better.

### PR DESCRIPTION
**Pull request by Genghius**
Follow up of #98, weather now displays much more information.
image

### CODE REVIEW

**Comment by Genghius** [comment]
Passes all tests, merge ready.

**Comment by Genghius** [comment]
image
new commit with a better format and a fix for the makefile.

**Comment by Genghius** [comment]
image
what is better out of these 3 formattings?

**Comment by Genghius** [comment]
image
REJOICE IN THE GLORY OF MY SED CHAIN YE MERE MORTALS!
TREMBLE YE MIGHTY!!!

**Comment by Genghius** [comment]
image
We are staying with this format caus it lets me flex the sed chain.

**Comment by sudocanttype** [comment]
Dang, nice work. Your sed chain is simply too good

**Comment by jhagas** [comment]
Wow! Great work! Bun can you add "weather condition" phrase inside of it?

**Comment by Genghius** [comment]
> Wow! Great work! Bun can you add "weather condition" phrase inside of it? Like i did in #98

sure.

**Comment by Genghius** [comment]
image
Done, its now merge ready, it has everything.

**Comment by Genghius** [comment]
image
Done, its now merge ready.

**Comment by Genghius** [comment]
image
sed chain btw.

**Comment by jhagas** [comment]
Works like a charm
```
$ tuxi weather Bojonegoro
---
Cloudy
24ºC	76ºF
Precipitation:	9%
Humidity:	95%
Wind:	6 km/h
4 mph
---
```

**Comment by Bugswriter** [comment]
awesome. Sorry for being late. Merging this in dev2

**Pull request merged**
