### PR TITLE
made 2nd lyrics option because original didnt always work for every song

### PR DESCRIPTION
**Pull request by sudocanttype**
Requests like "despacito lyrics" did not work. There is a bug where it has the "...More" in the song, and not sure how to fix that.

### CODE REVIEW

**Comment by Bugswriter** [comment]
I don't understand Does google give lyrics result on two places?

**Comment by Bugswriter** [comment]
if yes that's scary. I wish that's not the case with every feature.

**Comment by sudocanttype** [comment]
Yep, for me "div.bbVIQb" just did not exist for my song searches.

**Comment by Genghius** [comment]
> Yep, for me "div.bbVIQb" just did not exist for my song searches.

can you tell me which song did this happen with so i can see whats happening?

**Comment by Bugswriter** [comment]
> Yep, for me "div.bbVIQb" just did not exist for my song searches.

Woah, @Genghius you saw what he wrote. For him class name is different ? tell me which song I want to try my tuxi to find lyrics.

**Comment by sudocanttype** [comment]
ummmmmmmmmmmmmmmmmm 
image
This is with the base code

**Comment by Genghius** [comment]
image
seems like a problem caus u are using an old version.

**Comment by Genghius** [comment]
panacea PR works, it was an issue with the old version. this PR can be closed.

**Comment by sudocanttype** [comment]
Huh, I'm looking at the develop branch tuxi file right now, and it looks like it's still using ".bbVIQb". I'm gonna clone the development branch and test again, maybe it's just a problem with my computer

**Comment by Bugswriter** [comment]
I am getting despacito lyrics. Why he is not getting?

**Comment by Bugswriter** [comment]
> Huh, I'm looking at the develop branch tuxi file right now, and it looks like it's still using ".bbVIQb". I'm gonna clone the development branch and test again, maybe it's just a problem with my computer

Yes do it. I am getting every song I want.

**Comment by Bugswriter** [comment]
I just listened the whole song - "we will rock you"

`tuxi we will rock you lyrics | espeak -s 150`

**Comment by sudocanttype** [comment]
image
huh. Thats strange.

**Comment by colonvirus** [comment]
Where are you?
In the US?

**Comment by sudocanttype** [comment]
yep, us. What part of the world are you guys in?

**Comment by colonvirus** [comment]
Right, it doesn't work in the US

**Comment by Bugswriter** [comment]
I am Indian like you. are you using. .current version of develop? That is truly insane just. 
print the whole html and redirect it in tmp.html and tell me what you are getting? are you getting lyrics? If yes then why .. tuxi can't scrape it?

**Comment by colonvirus** [comment]
#23

**Comment by colonvirus** [comment]
Google shows lyrics in two different styles

**Comment by BeyondMagic** [comment]
Post the tmp.html like Bugswriter said.

**Comment by Bugswriter** [comment]
> Google shows lyrics in two different styles

I got this ..so that's why you started this pull request ..Right? After this are you getting .lyrics?

**Comment by sudocanttype** [comment]
[bruh.txt](https://github.com/Bugswriter/tuxi/files/6004767/bruh.txt)
ok heres the html of the search "./tuxi we will rock you lyrics "

**Comment by Bugswriter** [comment]
you are using VPN? I see you are being redirected.. means you are not getting any result from google ..this is fault in your Computer. make sure we are getting this issue because of two type of lyrics response and not because of your computer.

**Comment by colonvirus** [comment]
Before and after vpn

**Comment by sudocanttype** [comment]
Huh. That's strange. Maybe it just does not work in the US?

**Comment by colonvirus** [comment]
Yea, like I said, US has a different version

**Comment by sudocanttype** [comment]
image
interestingly gecgecgec works, but with other songs, it gives the wrong result, then no result. 
image

**Comment by Genghius** [comment]
This issue has already been fixed, it was due to having an old version of tuxi which broke lyrics scrapping.

**Comment by Bugswriter** [comment]
> Huh. That's strange. Maybe it just does not work in the US?

can't you see? when you use VPN . you don't get result you get a redirect .. that's is why no result also Using VPN is not changing your country everytime. sometimes You get issue like this redirect issue.

**Comment by colonvirus** [comment]
No, it hasn't been fixed
This is a different div


"ujudUb", same as the pr

**Comment by sudocanttype** [comment]
image
I'm not connected to a VPN though

**Comment by Bugswriter** [comment]
> No, it hasn't been fixed
> This is a different div
> 
> 
> "ujudUb", same as the pr

You search results is very different. 
Ok So We have two different .. ways of getting lyrics? 
That's it. Just add both ways and prioritize the current one. what's the Issue?
and please don't use VPN.

**Comment by sudocanttype** [comment]
Epic, all other functions seem to be working perfectly in the US

**Comment by Bugswriter** [comment]
> Epic, all other functions seem to be working perfectly in the US

Develop branch?

**Comment by sudocanttype** [comment]
yep, development branch
image

**Comment by Genghius** [comment]
send your testoutputs.txt file please.

**Comment by Bugswriter** [comment]
Can someone please tell me what I have to do with this pull request? Also this request is for main. I think there is a option in github which restrict ..making PR in main. 
PR in Develop.

**Comment by sudocanttype** [comment]
ok i can make another pr

**Comment by sudocanttype** [comment]
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6004948/testoutputs.txt)

**Comment by Genghius** [comment]
> [testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6004948/testoutputs.txt)

all seems good.

**Comment by Genghius** [comment]
> Can someone please tell me what I have to do with this pull request? Also this request is for main. I think there is a option in github which restrict ..making PR in main.
> PR in Develop.

do restrict PR in main plz. Also, i would recomend closing this PR... as the issue here seems to be more of a network issue by suer side than script side.

**Comment by Genghius** [comment]
ok, now that the other PR is going for develop, this PR should be closed.

**Pull request closed without merging**
