### PR TITLE
Better tuxi

### PR DESCRIPTION
**Pull request by owl4ce**
You can adjust it if it doesn't fit.

<p align="center"></p>

### CODE REVIEW

**Comment by owl4ce** [comment]
Wait a while, dependency checking only works in bash. I'll try to find out, or does anyone want to correct?

**Comment by Bugswriter** [comment]
your really did amazing job. Let me test. this .. I think I will merge.

**Comment by Bugswriter** [comment]
Umm I just merge another pull request ..improved few things like adding --compressed in curl to improve response also adding recode in list too. 
I am getting small merge conflicts .. can you take a look at this?

**Comment by Bugswriter** [comment]
I removed conflicts .. can I merge now?

**Comment by owl4ce** [comment]
Yeah
image

**Comment by Bugswriter** [comment]
Sorry but .. I think you should remove those 
--- 
before and after answer. 
because. . If someone want to script this. .He will have problem. Like If I got a list of celebs and I want to make a list of their birthdays. This will be issue ..

**Comment by colonvirus** [comment]
The colors are a problem. They'll show up as color codes in files, and can't be shown as a notification in something like dunst.

**Comment by owl4ce** [comment]
> Sorry but .. I think you should remove those
> " --- "
> before and after answer.
> because. . If someone want to script this. .He will have problem. Like If I got a list of celebs and I want to make a list of their birthdays. This will be issue ..

It's okay

**Comment by Bugswriter** [comment]
Also many people want to use this with dunst so they might don't want those "---"

**Comment by owl4ce** [comment]
So, will remove the color and "---"?

**Comment by colonvirus** [comment]
maybe add a --color=False flag?

**Comment by Bugswriter** [comment]
> So, will remove the color and "---"?

Yeah You are right. Colors will also be a issue .. I want my program to be extensible. I follow suckless philosophy.

**Comment by owl4ce** [comment]
Okay, wait for a while.

**Comment by Bugswriter** [comment]
yeah --color=False is brilliant .. this will save your ..

**Comment by Bugswriter** [comment]
But you should add this info when someone type just 'tuxi' so he will know.

**Comment by colonvirus** [comment]
--raw gives different results

`tuxi "height of mount everest" `                                                                                                                             
> Mount Everest is Earth's highest mountain above sea level, located
> in the Mahalangur Himal sub-range of the Himalayas. The ChinaâNepal
> border runs across its summit point. Its elevation of 8,848.86
> m was most recently established in 2020 by the Nepali
> and Chinese authorities.

`tuxi --raw "height of mount everest" ` 
> 8,848.86 meters


With a vpn connected to the US


`tuxi "height of mount everest" `                                                                                                                             
> The new height is 8,848.86m (29,032 ft). China's previous official
> measurement of 8,844.43m had put the mountain nearly four metres
> lower than Nepal's.

`tuxi --raw "height of mount everest" ` 
> 29,032â²

**Comment by owl4ce** [comment]
> --raw gives different results
> 
> `tuxi "height of mount everest" `
> 
> > Mount Everest is Earth's highest mountain above sea level, located
> > in the Mahalangur Himal sub-range of the Himalayas. The ChinaâNepal
> > border runs across its summit point. Its elevation of 8,848.86
> > m was most recently established in 2020 by the Nepali
> > and Chinese authorities.
> 
> `tuxi --raw "height of mount everest" `
> 
> > 8,848.86 meters
> 
> With a vpn connected to the US
> 
> `tuxi "height of mount everest" `
> 
> > The new height is 8,848.86m (29,032 ft). China's previous official
> > measurement of 8,844.43m had put the mountain nearly four metres
> > lower than Nepal's.
> 
> `tuxi --raw "height of mount everest" `
> 
> > 29,032â²

Yes, I still don't understand why that is ._.

**Comment by owl4ce** [comment]
I think because of this
```cfg
7 query="$*" && msg() { echo "> $*"; } && error() { echo "$*"; } && strip() { echo "$*"; }
```
that includes --raw into the curl query, I think.
https://github.com/owl4ce/tuxi/blob/d85c5321491b7ee99857d77d0a51cd65fff9301f/tuxi#L7

**Comment by colonvirus** [comment]
"${*:2}"

**Comment by colonvirus** [comment]
getopts would be better though, to add future options.

**Comment by owl4ce** [comment]
> getopts would be better though, to add future options, like -h, --help.

image

**Comment by owl4ce** [comment]
image

**Comment by colonvirus** [comment]
`case $1 in` limits options to the second argument though, and no multiple options ¯\\\_(ツ)_/¯
You could try getopts, or I'll do it after this gets merged.

**Comment by owl4ce** [comment]
I'll just end the commit here. 👍🏻

**Comment by Bugswriter** [comment]
are we ready to merge this?

**Comment by owl4ce** [comment]
> are we ready to merge this?

Yeah 👍🏻

**Pull request merged**
