### PR TITLE
Duplicate of #76

### PR DESCRIPTION
**Pull request by sudocanttype**

### CODE REVIEW

**Comment by Genghius** [comment]
Why is the duplicate needed?

**Comment by Genghius** [comment]
does the extra lyrics functions pass all tests?

**Comment by sudocanttype** [comment]
Yep, Bugwriter wanted the PR to go to the dev branch, not main

**Comment by sudocanttype** [comment]
And yes, the extra lyrics code does pass all tests

**Comment by Genghius** [comment]
nice.

**Comment by sudocanttype** [comment]
Also, you might want to just merge the tuxi file, and ignore the README edits

**Comment by Bugswriter** [comment]
Cool so I can merge this now? and  close the old PR https://github.com/Bugswriter/tuxi/pull/76

**Comment by sudocanttype** [comment]
Yep

**Comment by Bugswriter** [comment]
We are done with lyrics for now?

**Comment by sudocanttype** [comment]
I assume so, unless other problems arise

**Pull request merged**
