### PR TITLE
panacea 3 electric boogalo edition

### PR DESCRIPTION
**Pull request by Genghius**
image
-passed all tests
-debug mode from #77 added.
image
-issue #68 fixed completely
-issues #68 and #74 can now be closed.

### CODE REVIEW

**Comment by officialcactar** [comment]
see #56 
there is a new quality test script

**Comment by colonvirus** [comment]
That had some issues

**Comment by Genghius** [comment]
> That had some issues

wut?

**Comment by colonvirus** [comment]
Oh, @officialcactar had commented saying what happened to their version

**Comment by Genghius** [comment]
ok now im confused xd, is there any issue with this PR or not?

**Comment by Bugswriter** [comment]
Besides debug .. you fixed the dictionary functionality right?

**Comment by colonvirus** [comment]
> That had some issues

I meant @officialcactar's ./tuxiqualitytest.sh had issues, since I was replying to them.
But they deleted their comment, so my

> That had some issues

Looks stupid

**Comment by Bugswriter** [comment]
You added debug ? but I have another https://github.com/Bugswriter/tuxi/pull/77 PR for debug.

**Comment by Genghius** [comment]
> Besides debug .. you fixed the dictionary functionality right?

yes, the second screenshot is how dictionary is shown now, like a list, every definition is a new entry.

**Comment by Genghius** [comment]
> You added debug ? but I have another #77 PR for debug.

the debug i added is copied directly from #77

**Comment by Bugswriter** [comment]
So I can close that PR and merge this one. Right?
this will settle us for now.

**Comment by colonvirus** [comment]
why not both 👍
no merge conflict

**Comment by colonvirus** [comment]
Also, i added -v version to help

**Comment by Genghius** [comment]
> So I can close that PR and merge this one. Right?
> this will settle us for now.

just do both, they wont have conflict.

**Comment by Genghius** [comment]
AHHH??? they had conflicts?!?!? xd

**Comment by colonvirus** [comment]
lol

**Comment by Genghius** [comment]
oh, its just comments and spaces.

**Comment by Genghius** [comment]
should be easy to resolve.

**Comment by Bugswriter** [comment]
> AHHH??? they had conflicts?!?!? xd

I resolved the conflicts.

**Comment by Genghius** [comment]
xd

**Pull request merged**
