### PR TITLE
Add a man page, update Makefile to copy man page to path.

### PR DESCRIPTION
**Pull request by rushdabs**
I added a man page (tuxi.1) in the project root. 
In the Makefile, it copies the man page to path and uses gzip to compress it.

### CODE REVIEW

**Comment by Bugswriter** [comment]
Do we need this ? @colonvirus @officialcactar @owl4ce

**Comment by owl4ce** [comment]
That's better, I think.

**Comment by colonvirus** [comment]
You should add examples, cuz this just seems like a glorified help text

**Comment by Bugswriter** [comment]
> That's better, I think. But if a feature is added in tuxi, please also match readme and man pages.
> There will be more work here. Also, to curl means to stay single tuxi without man pages, etc.

We can add about our priority order and  how tuxi is working in man page

**Comment by owl4ce** [comment]
Also that's `make unistall` option doesn't define deleting `man pages` yet.

**Comment by Bugswriter** [comment]
Please give PR for develop branch ..not in main. 
I think I should restrict people to give PR in main.

**Comment by rushdabs** [comment]
> You should add examples, cuz this just seems like a glorified help text

Yes. I thought of doing so too. But I'm not so good at groff. I thought someone here could help me.

**Comment by rushdabs** [comment]
I'm closing this PR for now. Will create another in develop branch one after adding examples and necessary Makefile changes.

**Pull request closed without merging**
