### PR TITLE
updated test script

### PR DESCRIPTION
**Pull request by sudocanttype**
Added more diverse test cases, now it doesnt just output to a text file, also pops up

### CODE REVIEW

**Comment by sudocanttype** [comment]
@Bugswriter Can you test this script and see if it works in india?

**Comment by sudocanttype** [comment]
Oh wait nevermind this already got implemented to main. I just never noticed

**Comment by sudocanttype** [comment]
Nevermind I'm just really dumb. I made it so that it shows the output of the test once it's done

**Comment by Bugswriter** [comment]
You should use -r in test script .. So we can have some clean output in text file.

**Comment by sudocanttype** [comment]
-r? Where?

**Comment by Bugswriter** [comment]
when we use tuxi -r it will give raw output. .So this way ..our testoutput file doesn't contain those color codes.

**Comment by sudocanttype** [comment]
@Bugswriter Added a raw output option. I'm not adding a help option or anything because this isn't meant for general use, just us devs. I've tested it on my machine, works a-ok. Here's the output file 
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6018793/testoutputs.txt)

**Comment by sudocanttype** [comment]
@Bugswriter Can you check out the updated test script and see if the -r option is up to standards?

**Comment by Bugswriter** [comment]
Sorry I have an exam tomorrow. I ll check at tomorrow evening.

**Comment by sudocanttype** [comment]
Nah, it's fine. Exams are 100% more important than a minor update.

**Pull request merged**
