### PR TITLE
Fix for all issues PR. [merge ready]

### PR DESCRIPTION
**Pull request by Genghius**
Fixed most issues.
Added quality test

### CODE REVIEW

**Comment by Genghius** [comment]
image
Image of the test script btw.

**Comment by BeyondMagic** [comment]
image went wrong

**Comment by officialcactar** [comment]
> 
> 
> image
> Image of the test script btw.

lemme get my magnifying glass 🔎

**Comment by owl4ce** [comment]
Yeah, I stil got `a`
image

**Comment by BeyondMagic** [comment]
in `res1`, `zCubwf` is used for basic information like `tuxi christmas day`.

**Comment by owl4ce** [comment]
feature snippets parse problem 🤔 

2021-02-18-103023_1366x768_scrot

**Comment by BeyondMagic** [comment]
> featured snippets parse problem :thinking:

Is translation working there?

**Comment by owl4ce** [comment]
> > featured snippets parse problem thinking
> 
> Is translation working there?

Yeah
image

**Comment by BeyondMagic** [comment]
> RAW: https://raw.githubusercontent.com/Bugswriter/tuxi/ea6394d40edaf702311bb74fff5ddd6a972eb4f5/tuxi
> or
> RAW: https://raw.githubusercontent.com/Genghius/tuxi/main/tuxi
> Yeah

The second, I think selecting twice a class from Google will delay the updating of all the "scrappers" that tuxi currently have.

Using 
`trans="$(echo "$google_html" | pup 'pre.XcVN5d span:first-child json{}' | jq -r '.[1] | .text' | sed 's/null//g' | recode html..ISO-8859-1)"`
will make things easier for whoever is maintaining this when Google Search updates. Check RAW https://raw.githubusercontent.com/BeyondMagic/tuxi/main/tuxi

**Comment by owl4ce** [comment]
> > RAW: https://raw.githubusercontent.com/Bugswriter/tuxi/ea6394d40edaf702311bb74fff5ddd6a972eb4f5/tuxi
> > or
> > RAW: https://raw.githubusercontent.com/Genghius/tuxi/main/tuxi
> > Yeah
> 
> The second, I think selecting twice a class from Google will delay the updating of all the "scrappers" that tuxi currently have.
> 
> Using
> `trans="$(echo "$google_html" | pup 'pre.XcVN5d span:first-child json{}' | jq -r '.[1] | .text' | sed 's/null//g' | recode html..ISO-8859-1)"`
> will make things easier for whoever is maintaining this when Google Search updates. Check RAW https://raw.githubusercontent.com/BeyondMagic/tuxi/main/tuxi

2021-02-18-114251_1366x768_scrot

image

**Comment by BeyondMagic** [comment]
It seems that it's working great then :)

**Comment by owl4ce** [comment]
featured snippets too

image

**Comment by owl4ce** [comment]
> It seems that it's working great then :)

@BeyondMagic 
I thought yours was ready to merge 👍🏻 

image

**Comment by BeyondMagic** [comment]
> @BeyondMagic
> I thought yours was ready to merge 👍🏻

I'll reopen when #39 is merged (or someone will) to merge #40. It shouldn't have any conflicts between both and after that, I hope.

**Comment by colonvirus** [comment]
The "a" was me trynna find out what each snippet does 😅

**Comment by Genghius** [comment]
> featured snippets parse problem 🤔
> 
> 2021-02-18-103023_1366x768_scrot

i see the `a` at the begining of the return string, i will fix it in 20 minutes when i wake up.

**Comment by Genghius** [comment]
> The "a" was me trynna find out what each snippet does 😅

I think i was also getting the a.

**Comment by colonvirus** [comment]
just delete the a behind $feat

**Comment by Genghius** [comment]
> just delete the a behind $feat

ok, i can do that from my phone :D

**Comment by Genghius** [comment]
> > just delete the a behind $feat
> 
> ok, i can do that from my phone :D

this will btw, oficially make me an "android programmer"

**Comment by owl4ce** [comment]
> > > just delete the a behind $feat
> > 
> > 
> > ok, i can do that from my phone :D
> 
> this will btw, oficially make me an "android programmer"

I see a lot of people becoming "android developers" with vim on termux. Make sense.
**Nothing wrong with that.**

**Comment by BeyondMagic** [comment]
> i will fix it in 20 minutes when i wake up.

lucid dreams be like

**Comment by Genghius** [comment]
> > i will fix it in 20 minutes when i wake up.
> 
> lucid dreams be like

sleeping with one eye open for when this PR gets merged.

**Comment by Genghius** [comment]
> in `res1`, `zCubwf` (`tuxi` file, line `173`) is used for basic information like `tuxi christmas day`.

commited.

**Comment by colonvirus** [comment]
"christmass day"
One more commit 😂

**Comment by Genghius** [comment]
> "christmass day"
> One more commit 😂

I SWEAR I WILL....
🤣

**Comment by Genghius** [comment]
no one will know anyway, better leave it there. anyway we already have "linux torvalds"

**Comment by colonvirus** [comment]
I'd just like to interject for a moment. What you're referring to as Linux Torvalds, is in fact, GNU/Linux Torvalds, or as I've recently taken to calling it, GNU plus Linux Torvalds.

**Comment by Genghius** [comment]
> I'd just like to interject for a moment. What you're referring to as Linux Torvalds, is in fact, GNU/Linux Torvalds, or as I've recently taken to calling it, GNU plus Linux Torvalds.

And thenceforth, this PR is ready to be merged.

**Comment by colonvirus** [comment]
Could you also rearrange the snippet priority, and rename the "?" as "Basic Answers"

**Comment by Genghius** [comment]
> Could you also rearrange the snippet priority, and rename the "?" as "Basic Answers"?

done in latest commit

**Comment by colonvirus** [comment]
The commented part

```
## Snippet Priority ##
# Did you mean
# Math
# Knowledge Graph - top
# ?
# Rich Answers
# Featured Snippets
# Google Translate
# Lyrics
# Knowledge Graph - right
```

**Comment by Genghius** [comment]
> The commented part
> 
> ```
> ## Snippet Priority ##
> # Did you mean
> # Math
> # Knowledge Graph - top
> # ?
> # Rich Answers
> # Featured Snippets
> # Google Translate
> # Lyrics
> # Knowledge Graph - right
> ```

MAY LIGTHING SPLIT ME AND MY SKIN BE SET ON FIRE!
🤣 
this will be the true last last commit.

**Comment by colonvirus** [comment]
Should we make a "scraper pr template" for future additions?

**Comment by Genghius** [comment]
11 commits. it took 11 commits to reach this point. but now i can say with certainty this is the last commit.

**Comment by Genghius** [comment]
> Should we make a "scraper pr template" for future additions?

**LAST COMMIT**

**Comment by colonvirus** [comment]
No no, I meant as a template for the develop branch.
Also, the readme for contributing should point to the develop branch.

**Comment by Genghius** [comment]
> No no, I meant as a template for the develop branch.
> Also, the readme for contributing should point to the develop branch.
> We'll do this later.

yes, thats good, PR that when u can.

**Comment by Genghius** [comment]
Not that I'm trynna flex, but apparently I only need to sleep 5 hours/day
image

**Comment by owl4ce** [comment]
Programmers only need 1 hour of sleep 😆 
A few days later ..

**Comment by owl4ce** [comment]
https://github.com/Bugswriter/tuxi/pull/44

**Comment by Genghius** [comment]
> #44

all it takes to merge with this one is changing variable names.

**Comment by Bugswriter** [comment]
woah so many things in just one PR. So I am merging this in developer branch and lets test this properly. Then this will go to main branch.

**Comment by Bugswriter** [comment]
I see we have so many awesome new features like. . whether and currency. somebody give 
One users ask for quotation support - `" pup 'div[data-mh="-1"] i text{}'"`
Should I open a issue for this?

**Comment by Genghius** [comment]
> I see we have so many awesome new features like. . whether and currency. somebody give
> One users ask for quotation support - `" pup 'div[data-mh="-1"] i text{}'"`
> Should I open a issue for this?

please do open an issue for it.
also, could you check if #40 can be merged directly to this too?

**Comment by Bugswriter** [comment]
So after merge I tested working like charm but. .not getting whether . Did you guys added whether?

**Comment by Genghius** [comment]
we didnt, that was in #40

**Comment by Genghius** [comment]
@BeyondMagic was waiting for this one to be merged so he could adapt his weather one to merge directly to this.

**Comment by Bugswriter** [comment]
also are we using google to get whether. I guess he posted SS of some other service?

**Comment by Bugswriter** [comment]
relying on other service for something google can do is risky due to higher chances of website CSS change and program breaks.

**Comment by Genghius** [comment]
Yes, I see. let's wait until he rewrites it and then we'll see.

**Pull request merged**
