### PR TITLE
fixed previous merge

### PR DESCRIPTION
**Pull request by colonvirus**

### CODE REVIEW

**Comment by Bugswriter** [comment]
what's on earth is this now?

**Comment by colonvirus** [comment]
I forgot to rename the variables lol

**Comment by Genghius** [comment]
> what's on earth is this now?

i think he also added description for my google translate scrap

**Comment by Bugswriter** [comment]
I merged this. BTW you guys are doing amazing job.

**Comment by owl4ce** [comment]
Hi guys, don't forget to change README if tuxi `-h` argument changes :)

**Pull request merged**
